import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";

const ROUTES_API_URL =
  "https://gateway-api-mainnet.gobob.xyz/v1/get-routes";

const NON_EVM_CHAINS: Record<string, string> = {
  bitcoin: "BTC",
  aptos: "WBTC",
};

const capitalize = (s: string) =>
  s === "bsc" ? "BSC" : s.charAt(0).toUpperCase() + s.slice(1);

const truncate = (addr: string) =>
  addr.length <= 12 ? addr : `${addr.slice(0, 6)}...${addr.slice(-4)}`;

async function main() {
  const response = await fetch(ROUTES_API_URL);
  if (!response.ok) throw new Error(`Failed to fetch routes: ${response.status}`);
  const routes: { srcChain: string; srcToken: string; dstChain: string; dstToken: string }[] =
    await response.json();

  const tokenlistPath = resolve(dirname(new URL(import.meta.url).pathname), "../../../tokenlist/tokenlist.json");
  const { tokens } = JSON.parse(readFileSync(tokenlistPath, "utf-8"));

  // Address-based lookup — no chain ID mapping needed
  const symbolOf = new Map<string, string>();
  for (const t of tokens) {
    const addr = t.address.toLowerCase();
    if (!symbolOf.has(addr)) symbolOf.set(addr, t.symbol);
  }

  const resolve_ = (chain: string, addr: string) =>
    NON_EVM_CHAINS[chain] ?? symbolOf.get(addr.toLowerCase()) ?? (() => {
      console.warn(`  Warning: unknown token ${addr} on ${chain}`);
      return "Unknown";
    })();

  // Group by source chain
  const groups = new Map<string, typeof routes>();
  for (const r of routes) {
    (groups.get(r.srcChain) ?? (() => { const a: typeof routes = []; groups.set(r.srcChain, a); return a; })()).push(r);
  }

  let mdx = `---
title: "Supported Routes & Assets"
description: "A comprehensive list of all supported chains and token routes available through the BOB Gateway."
icon: "route"
---

{/* This page is auto-generated by docs/gateway/scripts/generate-routes.ts. Do not edit manually. */}

The following tables list all supported routes available through the BOB Gateway API.
This page is **auto-generated** from the live [\`/v1/get-routes\`](/api-reference/overview) endpoint
and the [BOB tokenlist](https://github.com/bob-collective/bob/blob/master/tokenlist/tokenlist.json)
to ensure it stays up to date.

**Last updated:** ${new Date().toISOString().split("T")[0]}

`;

  for (const chain of [...groups.keys()].sort()) {
    const chainRoutes = groups.get(chain)!;
    chainRoutes.sort((a, b) => a.dstChain.localeCompare(b.dstChain) || a.srcToken.localeCompare(b.srcToken));

    mdx += `## From ${capitalize(chain)}\n\n`;
    mdx += `| Source Token | Destination Chain | Destination Token | Source Token Address | Destination Token Address |\n`;
    mdx += `|---|---|---|---|---|\n`;

    for (const r of chainRoutes) {
      const src = resolve_(r.srcChain, r.srcToken);
      const dst = resolve_(r.dstChain, r.dstToken);
      const srcDisplay = src === "Unknown" ? `Unknown (${truncate(r.srcToken)})` : src;
      const dstDisplay = dst === "Unknown" ? `Unknown (${truncate(r.dstToken)})` : dst;
      mdx += `| ${srcDisplay} | ${capitalize(r.dstChain)} | ${dstDisplay} | \`${truncate(r.srcToken)}\` | \`${truncate(r.dstToken)}\` |\n`;
    }
    mdx += `\n`;
  }

  const outputPath = resolve(dirname(new URL(import.meta.url).pathname), "../gateway/supported-routes.mdx");
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, mdx, "utf-8");
  console.log(`Generated ${outputPath} (${routes.length} routes, ${tokens.length} tokens)`);
}

main().catch((err) => { console.error(err); process.exit(1); });
