import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";

const ROUTES_API_URL =
  "https://gateway-api-mainnet.gobob.xyz/v1/get-routes";

interface Route {
  srcChain: string;
  srcToken: string;
  dstChain: string;
  dstToken: string;
}

interface Token {
  chainId: number;
  address: string;
  name: string;
  symbol: string;
  decimals: number;
  logoURI?: string;
}

interface TokenList {
  tokens: Token[];
}

interface ResolvedRoute {
  srcChain: string;
  srcTokenSymbol: string;
  srcTokenAddress: string;
  dstChain: string;
  dstTokenSymbol: string;
  dstTokenAddress: string;
}

// Non-EVM chains where token addresses can't be resolved via the tokenlist
const NON_EVM_CHAINS: Record<string, string> = {
  bitcoin: "BTC",
  aptos: "WBTC",
};

function capitalizeChain(chain: string): string {
  if (chain === "bsc") return "BSC";
  return chain.charAt(0).toUpperCase() + chain.slice(1);
}

function truncateAddress(address: string): string {
  if (address.length <= 12) return address;
  return `${address.slice(0, 6)}...${address.slice(-4)}`;
}

async function main() {
  // Fetch routes from the API
  console.log("Fetching routes from gateway API...");
  const response = await fetch(ROUTES_API_URL);
  if (!response.ok) {
    throw new Error(
      `Failed to fetch routes: ${response.status} ${response.statusText}`
    );
  }
  const routes: Route[] = await response.json();
  console.log(`Fetched ${routes.length} routes.`);

  // Load tokenlist
  const tokenlistPath = resolve(
    dirname(new URL(import.meta.url).pathname),
    "../../../tokenlist/tokenlist.json"
  );
  console.log(`Loading tokenlist from ${tokenlistPath}...`);
  const tokenlist: TokenList = JSON.parse(
    readFileSync(tokenlistPath, "utf-8")
  );
  console.log(`Loaded ${tokenlist.tokens.length} tokens.`);

  // Build token lookup by address (case-insensitive).
  // Since each token has a unique contract address, we don't need chain IDs to resolve symbols.
  const tokenByAddress = new Map<string, Token>();
  for (const token of tokenlist.tokens) {
    const addr = token.address.toLowerCase();
    if (!tokenByAddress.has(addr)) {
      tokenByAddress.set(addr, token);
    }
  }

  function resolveSymbol(chain: string, address: string): string {
    if (chain in NON_EVM_CHAINS) return NON_EVM_CHAINS[chain];
    const token = tokenByAddress.get(address.toLowerCase());
    if (token) return token.symbol;
    console.warn(`  Warning: unknown token ${address} on ${chain}`);
    return "Unknown";
  }

  // Resolve routes
  const resolvedRoutes: ResolvedRoute[] = routes.map((route) => ({
    srcChain: route.srcChain,
    srcTokenSymbol: resolveSymbol(route.srcChain, route.srcToken),
    srcTokenAddress: route.srcToken,
    dstChain: route.dstChain,
    dstTokenSymbol: resolveSymbol(route.dstChain, route.dstToken),
    dstTokenAddress: route.dstToken,
  }));

  // Group routes by source chain
  const groupedRoutes = new Map<string, ResolvedRoute[]>();
  for (const route of resolvedRoutes) {
    const group = groupedRoutes.get(route.srcChain) || [];
    group.push(route);
    groupedRoutes.set(route.srcChain, group);
  }

  // Sort source chains alphabetically
  const sortedChains = Array.from(groupedRoutes.keys()).sort();

  // Generate MDX content
  let mdx = `---
title: "Supported Routes & Assets"
description: "A comprehensive list of all supported chains and token routes available through the BOB Gateway."
icon: "route"
---

{/* This page is auto-generated by docs/gateway/scripts/generate-routes.ts. Do not edit manually. */}

The following tables list all supported routes available through the BOB Gateway API.
This page is **auto-generated** from the live [\`/v1/get-routes\`](/api-reference/overview) endpoint
and the [BOB tokenlist](https://github.com/bob-collective/bob/blob/master/tokenlist/tokenlist.json)
to ensure it stays up to date.

**Last updated:** ${new Date().toISOString().split("T")[0]}

`;

  for (const chain of sortedChains) {
    const chainRoutes = groupedRoutes.get(chain)!;
    const displayChain = capitalizeChain(chain);

    mdx += `## From ${displayChain}\n\n`;
    mdx += `| Source Token | Destination Chain | Destination Token | Source Token Address | Destination Token Address |\n`;
    mdx += `|---|---|---|---|---|\n`;

    // Sort routes within each group by destination chain, then source token
    chainRoutes.sort((a, b) => {
      const chainCmp = a.dstChain.localeCompare(b.dstChain);
      if (chainCmp !== 0) return chainCmp;
      return a.srcTokenSymbol.localeCompare(b.srcTokenSymbol);
    });

    for (const route of chainRoutes) {
      const srcSymbol =
        route.srcTokenSymbol === "Unknown"
          ? `Unknown (${truncateAddress(route.srcTokenAddress)})`
          : route.srcTokenSymbol;
      const dstSymbol =
        route.dstTokenSymbol === "Unknown"
          ? `Unknown (${truncateAddress(route.dstTokenAddress)})`
          : route.dstTokenSymbol;
      const dstChainDisplay = capitalizeChain(route.dstChain);
      const srcAddr = `\`${truncateAddress(route.srcTokenAddress)}\``;
      const dstAddr = `\`${truncateAddress(route.dstTokenAddress)}\``;

      mdx += `| ${srcSymbol} | ${dstChainDisplay} | ${dstSymbol} | ${srcAddr} | ${dstAddr} |\n`;
    }

    mdx += `\n`;
  }

  // Write the MDX file
  const outputPath = resolve(
    dirname(new URL(import.meta.url).pathname),
    "../gateway/supported-routes.mdx"
  );
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, mdx, "utf-8");
  console.log(`Generated ${outputPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
