/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
    OrderStatusToJSONTyped,
} from './OrderStatus';
import type { TxInfo } from './TxInfo';
import {
    TxInfoFromJSON,
    TxInfoFromJSONTyped,
    TxInfoToJSON,
    TxInfoToJSONTyped,
} from './TxInfo';
import type { ChainTxInfo } from './ChainTxInfo';
import {
    ChainTxInfoFromJSON,
    ChainTxInfoFromJSONTyped,
    ChainTxInfoToJSON,
    ChainTxInfoToJSONTyped,
} from './ChainTxInfo';
import type { GatewayTokenAmount } from './GatewayTokenAmount';
import {
    GatewayTokenAmountFromJSON,
    GatewayTokenAmountFromJSONTyped,
    GatewayTokenAmountToJSON,
    GatewayTokenAmountToJSONTyped,
} from './GatewayTokenAmount';

/**
 * 
 * @export
 * @interface GatewayOrderInfoOneOf1Offramp
 */
export interface GatewayOrderInfoOneOf1Offramp {
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    amount: GatewayTokenAmount;
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    bitcoinExplorerUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    bobExplorerUrl: string;
    /**
     * 
     * @type {TxInfo}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    bumpFeeTx?: TxInfo | null;
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    contractId: string;
    /**
     * 
     * @type {ChainTxInfo}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    dstInfo: ChainTxInfo;
    /**
     * 
     * @type {number}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    estimatedTimeInSecs?: number | null;
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    fees: GatewayTokenAmount;
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    offrampRegistryAddress: string;
    /**
     * 
     * @type {TxInfo}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    refundOrderTx?: TxInfo | null;
    /**
     * 
     * @type {ChainTxInfo}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    srcInfo: ChainTxInfo;
    /**
     * 
     * @type {OrderStatus}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    status: OrderStatus;
    /**
     * 
     * @type {number}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    timestamp: number;
}



/**
 * Check if a given object implements the GatewayOrderInfoOneOf1Offramp interface.
 */
export function instanceOfGatewayOrderInfoOneOf1Offramp(value: object): value is GatewayOrderInfoOneOf1Offramp {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('bobExplorerUrl' in value) || value['bobExplorerUrl'] === undefined) return false;
    if (!('contractId' in value) || value['contractId'] === undefined) return false;
    if (!('dstInfo' in value) || value['dstInfo'] === undefined) return false;
    if (!('fees' in value) || value['fees'] === undefined) return false;
    if (!('offrampRegistryAddress' in value) || value['offrampRegistryAddress'] === undefined) return false;
    if (!('srcInfo' in value) || value['srcInfo'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function GatewayOrderInfoOneOf1OfframpFromJSON(json: any): GatewayOrderInfoOneOf1Offramp {
    return GatewayOrderInfoOneOf1OfframpFromJSONTyped(json, false);
}

export function GatewayOrderInfoOneOf1OfframpFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderInfoOneOf1Offramp {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': GatewayTokenAmountFromJSON(json['amount']),
        'bitcoinExplorerUrl': json['bitcoin_explorer_url'] == null ? undefined : json['bitcoin_explorer_url'],
        'bobExplorerUrl': json['bob_explorer_url'],
        'bumpFeeTx': json['bump_fee_tx'] == null ? undefined : TxInfoFromJSON(json['bump_fee_tx']),
        'contractId': json['contract_id'],
        'dstInfo': ChainTxInfoFromJSON(json['dst_info']),
        'estimatedTimeInSecs': json['estimated_time_in_secs'] == null ? undefined : json['estimated_time_in_secs'],
        'fees': GatewayTokenAmountFromJSON(json['fees']),
        'offrampRegistryAddress': json['offramp_registry_address'],
        'refundOrderTx': json['refund_order_tx'] == null ? undefined : TxInfoFromJSON(json['refund_order_tx']),
        'srcInfo': ChainTxInfoFromJSON(json['src_info']),
        'status': OrderStatusFromJSON(json['status']),
        'timestamp': json['timestamp'],
    };
}

export function GatewayOrderInfoOneOf1OfframpToJSON(json: any): GatewayOrderInfoOneOf1Offramp {
    return GatewayOrderInfoOneOf1OfframpToJSONTyped(json, false);
}

export function GatewayOrderInfoOneOf1OfframpToJSONTyped(value?: GatewayOrderInfoOneOf1Offramp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': GatewayTokenAmountToJSON(value['amount']),
        'bitcoin_explorer_url': value['bitcoinExplorerUrl'],
        'bob_explorer_url': value['bobExplorerUrl'],
        'bump_fee_tx': TxInfoToJSON(value['bumpFeeTx']),
        'contract_id': value['contractId'],
        'dst_info': ChainTxInfoToJSON(value['dstInfo']),
        'estimated_time_in_secs': value['estimatedTimeInSecs'],
        'fees': GatewayTokenAmountToJSON(value['fees']),
        'offramp_registry_address': value['offrampRegistryAddress'],
        'refund_order_tx': TxInfoToJSON(value['refundOrderTx']),
        'src_info': ChainTxInfoToJSON(value['srcInfo']),
        'status': OrderStatusToJSON(value['status']),
        'timestamp': value['timestamp'],
    };
}

