/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayErrorCode } from './GatewayErrorCode';
import {
    GatewayErrorCodeFromJSON,
    GatewayErrorCodeFromJSONTyped,
    GatewayErrorCodeToJSON,
    GatewayErrorCodeToJSONTyped,
} from './GatewayErrorCode';
import type { GatewayErrorDetails } from './GatewayErrorDetails';
import {
    GatewayErrorDetailsFromJSON,
    GatewayErrorDetailsFromJSONTyped,
    GatewayErrorDetailsToJSON,
    GatewayErrorDetailsToJSONTyped,
} from './GatewayErrorDetails';

/**
 * Structured error response that the frontend can parse.
 * Contains an error code, human-readable message, and optional structured details.
 * @export
 * @interface GatewayError
 */
export interface GatewayError {
    /**
     * Stable error code for frontend parsing
     * @type {GatewayErrorCode}
     * @memberof GatewayError
     */
    code: GatewayErrorCode;
    /**
     * Optional structured details specific to the error type
     * @type {GatewayErrorDetails}
     * @memberof GatewayError
     */
    details?: GatewayErrorDetails | null;
    /**
     * Human-readable error message
     * @type {string}
     * @memberof GatewayError
     */
    error: string;
}



/**
 * Check if a given object implements the GatewayError interface.
 */
export function instanceOfGatewayError(value: object): value is GatewayError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GatewayErrorFromJSON(json: any): GatewayError {
    return GatewayErrorFromJSONTyped(json, false);
}

export function GatewayErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': GatewayErrorCodeFromJSON(json['code']),
        'details': json['details'] == null ? undefined : GatewayErrorDetailsFromJSON(json['details']),
        'error': json['error'],
    };
}

export function GatewayErrorToJSON(json: any): GatewayError {
    return GatewayErrorToJSONTyped(json, false);
}

export function GatewayErrorToJSONTyped(value?: GatewayError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': GatewayErrorCodeToJSON(value['code']),
        'details': GatewayErrorDetailsToJSON(value['details']),
        'error': value['error'],
    };
}

