/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayErrorDetailsOneOf5
 */
export interface GatewayErrorDetailsOneOf5 {
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsOneOf5
     */
    limit: string;
}

/**
 * Check if a given object implements the GatewayErrorDetailsOneOf5 interface.
 */
export function instanceOfGatewayErrorDetailsOneOf5(value: object): value is GatewayErrorDetailsOneOf5 {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function GatewayErrorDetailsOneOf5FromJSON(json: any): GatewayErrorDetailsOneOf5 {
    return GatewayErrorDetailsOneOf5FromJSONTyped(json, false);
}

export function GatewayErrorDetailsOneOf5FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorDetailsOneOf5 {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
    };
}

export function GatewayErrorDetailsOneOf5ToJSON(json: any): GatewayErrorDetailsOneOf5 {
    return GatewayErrorDetailsOneOf5ToJSONTyped(json, false);
}

export function GatewayErrorDetailsOneOf5ToJSONTyped(value?: GatewayErrorDetailsOneOf5 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
    };
}

