/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayUserTokenTransfer
 */
export interface GatewayUserTokenTransfer {
    /**
     * 
     * @type {string}
     * @memberof GatewayUserTokenTransfer
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayUserTokenTransfer
     */
    chain: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayUserTokenTransfer
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayUserTokenTransfer
     */
    txHash: string;
}

/**
 * Check if a given object implements the GatewayUserTokenTransfer interface.
 */
export function instanceOfGatewayUserTokenTransfer(value: object): value is GatewayUserTokenTransfer {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    return true;
}

export function GatewayUserTokenTransferFromJSON(json: any): GatewayUserTokenTransfer {
    return GatewayUserTokenTransferFromJSONTyped(json, false);
}

export function GatewayUserTokenTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayUserTokenTransfer {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'chain': json['chain'],
        'token': json['token'],
        'txHash': json['txHash'],
    };
}

export function GatewayUserTokenTransferToJSON(json: any): GatewayUserTokenTransfer {
    return GatewayUserTokenTransferToJSONTyped(json, false);
}

export function GatewayUserTokenTransferToJSONTyped(value?: GatewayUserTokenTransfer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'chain': value['chain'],
        'token': value['token'],
        'txHash': value['txHash'],
    };
}

