/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Solana transaction returned on V3 create-order (offramp / token-swap).
 * 
 * `transaction` is base64-encoded bincode serialization of an unsigned `VersionedTransaction`.
 * Clients must decode, sign, re-serialize, and broadcast — do not sign the base64 string directly.
 * @export
 * @interface GatewaySolanaTx
 */
export interface GatewaySolanaTx {
    /**
     * 
     * @type {number}
     * @memberof GatewaySolanaTx
     */
    chainId: number;
    /**
     * 
     * @type {string}
     * @memberof GatewaySolanaTx
     */
    transaction: string;
}

/**
 * Check if a given object implements the GatewaySolanaTx interface.
 */
export function instanceOfGatewaySolanaTx(value: object): value is GatewaySolanaTx {
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('transaction' in value) || value['transaction'] === undefined) return false;
    return true;
}

export function GatewaySolanaTxFromJSON(json: any): GatewaySolanaTx {
    return GatewaySolanaTxFromJSONTyped(json, false);
}

export function GatewaySolanaTxFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewaySolanaTx {
    if (json == null) {
        return json;
    }
    return {
        
        'chainId': json['chainId'],
        'transaction': json['transaction'],
    };
}

export function GatewaySolanaTxToJSON(json: any): GatewaySolanaTx {
    return GatewaySolanaTxToJSONTyped(json, false);
}

export function GatewaySolanaTxToJSONTyped(value?: GatewaySolanaTx | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chainId': value['chainId'],
        'transaction': value['transaction'],
    };
}

