/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayCreateOrderOneOfOnramp
 */
export interface GatewayCreateOrderOneOfOnramp {
    /**
     * Bitcoin address to pay to
     * @type {string}
     * @memberof GatewayCreateOrderOneOfOnramp
     */
    address: string;
    /**
     * Optional OP_RETURN data
     * @type {string}
     * @memberof GatewayCreateOrderOneOfOnramp
     */
    opReturnData?: string | null;
    /**
     * Unique order id
     * @type {string}
     * @memberof GatewayCreateOrderOneOfOnramp
     */
    orderId: string;
    /**
     * Bitcoin PSBT
     * @type {string}
     * @memberof GatewayCreateOrderOneOfOnramp
     */
    psbt: string;
}

/**
 * Check if a given object implements the GatewayCreateOrderOneOfOnramp interface.
 */
export function instanceOfGatewayCreateOrderOneOfOnramp(value: object): value is GatewayCreateOrderOneOfOnramp {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('psbt' in value) || value['psbt'] === undefined) return false;
    return true;
}

export function GatewayCreateOrderOneOfOnrampFromJSON(json: any): GatewayCreateOrderOneOfOnramp {
    return GatewayCreateOrderOneOfOnrampFromJSONTyped(json, false);
}

export function GatewayCreateOrderOneOfOnrampFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayCreateOrderOneOfOnramp {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'opReturnData': json['op_return_data'] == null ? undefined : json['op_return_data'],
        'orderId': json['order_id'],
        'psbt': json['psbt'],
    };
}

export function GatewayCreateOrderOneOfOnrampToJSON(json: any): GatewayCreateOrderOneOfOnramp {
    return GatewayCreateOrderOneOfOnrampToJSONTyped(json, false);
}

export function GatewayCreateOrderOneOfOnrampToJSONTyped(value?: GatewayCreateOrderOneOfOnramp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'op_return_data': value['opReturnData'],
        'order_id': value['orderId'],
        'psbt': value['psbt'],
    };
}

