/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayOrderStatusOneOf1Failed } from './GatewayOrderStatusOneOf1Failed';
import {
    GatewayOrderStatusOneOf1FailedFromJSON,
    GatewayOrderStatusOneOf1FailedFromJSONTyped,
    GatewayOrderStatusOneOf1FailedToJSON,
    GatewayOrderStatusOneOf1FailedToJSONTyped,
} from './GatewayOrderStatusOneOf1Failed';

/**
 * 
 * @export
 * @interface GatewayOrderStatusOneOf1
 */
export interface GatewayOrderStatusOneOf1 {
    /**
     * 
     * @type {GatewayOrderStatusOneOf1Failed}
     * @memberof GatewayOrderStatusOneOf1
     */
    failed: GatewayOrderStatusOneOf1Failed;
}

/**
 * Check if a given object implements the GatewayOrderStatusOneOf1 interface.
 */
export function instanceOfGatewayOrderStatusOneOf1(value: object): value is GatewayOrderStatusOneOf1 {
    if (!('failed' in value) || value['failed'] === undefined) return false;
    return true;
}

export function GatewayOrderStatusOneOf1FromJSON(json: any): GatewayOrderStatusOneOf1 {
    return GatewayOrderStatusOneOf1FromJSONTyped(json, false);
}

export function GatewayOrderStatusOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderStatusOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'failed': GatewayOrderStatusOneOf1FailedFromJSON(json['failed']),
    };
}

export function GatewayOrderStatusOneOf1ToJSON(json: any): GatewayOrderStatusOneOf1 {
    return GatewayOrderStatusOneOf1ToJSONTyped(json, false);
}

export function GatewayOrderStatusOneOf1ToJSONTyped(value?: GatewayOrderStatusOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failed': GatewayOrderStatusOneOf1FailedToJSON(value['failed']),
    };
}

