/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GatewayQuoteV2OneOf } from './GatewayQuoteV2OneOf';
import {
    instanceOfGatewayQuoteV2OneOf,
    GatewayQuoteV2OneOfFromJSON,
    GatewayQuoteV2OneOfFromJSONTyped,
    GatewayQuoteV2OneOfToJSON,
} from './GatewayQuoteV2OneOf';
import type { GatewayQuoteV2OneOf1 } from './GatewayQuoteV2OneOf1';
import {
    instanceOfGatewayQuoteV2OneOf1,
    GatewayQuoteV2OneOf1FromJSON,
    GatewayQuoteV2OneOf1FromJSONTyped,
    GatewayQuoteV2OneOf1ToJSON,
} from './GatewayQuoteV2OneOf1';
import type { GatewayQuoteV2OneOf2 } from './GatewayQuoteV2OneOf2';
import {
    instanceOfGatewayQuoteV2OneOf2,
    GatewayQuoteV2OneOf2FromJSON,
    GatewayQuoteV2OneOf2FromJSONTyped,
    GatewayQuoteV2OneOf2ToJSON,
} from './GatewayQuoteV2OneOf2';

/**
 * @type GatewayQuoteV2
 * Gateway quote.
 * @export
 */
export type GatewayQuoteV2 = GatewayQuoteV2OneOf | GatewayQuoteV2OneOf1 | GatewayQuoteV2OneOf2;

export function GatewayQuoteV2FromJSON(json: any): GatewayQuoteV2 {
    return GatewayQuoteV2FromJSONTyped(json, false);
}

export function GatewayQuoteV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayQuoteV2 {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGatewayQuoteV2OneOf(json)) {
        return GatewayQuoteV2OneOfFromJSONTyped(json, true);
    }
    if (instanceOfGatewayQuoteV2OneOf1(json)) {
        return GatewayQuoteV2OneOf1FromJSONTyped(json, true);
    }
    if (instanceOfGatewayQuoteV2OneOf2(json)) {
        return GatewayQuoteV2OneOf2FromJSONTyped(json, true);
    }
    return {} as any;
}

export function GatewayQuoteV2ToJSON(json: any): any {
    return GatewayQuoteV2ToJSONTyped(json, false);
}

export function GatewayQuoteV2ToJSONTyped(value?: GatewayQuoteV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGatewayQuoteV2OneOf(value)) {
        return GatewayQuoteV2OneOfToJSON(value as GatewayQuoteV2OneOf);
    }
    if (instanceOfGatewayQuoteV2OneOf1(value)) {
        return GatewayQuoteV2OneOf1ToJSON(value as GatewayQuoteV2OneOf1);
    }
    if (instanceOfGatewayQuoteV2OneOf2(value)) {
        return GatewayQuoteV2OneOf2ToJSON(value as GatewayQuoteV2OneOf2);
    }
    return {};
}

