/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GatewayOnrampFeeBreakdown
 */
export interface GatewayOnrampFeeBreakdown {
    /**
     *
     * @type {string}
     * @memberof GatewayOnrampFeeBreakdown
     */
    affiliateFee: string;
    /**
     *
     * @type {string}
     * @memberof GatewayOnrampFeeBreakdown
     */
    executionFee: string;
    /**
     *
     * @type {string}
     * @memberof GatewayOnrampFeeBreakdown
     */
    layerzeroFee: string;
    /**
     *
     * @type {string}
     * @memberof GatewayOnrampFeeBreakdown
     */
    protocolFee: string;
    /**
     *
     * @type {string}
     * @memberof GatewayOnrampFeeBreakdown
     */
    solverFee: string;
}

/**
 * Check if a given object implements the GatewayOnrampFeeBreakdown interface.
 */
export function instanceOfGatewayOnrampFeeBreakdown(value: object): value is GatewayOnrampFeeBreakdown {
    if (!('affiliateFee' in value) || value['affiliateFee'] === undefined) return false;
    if (!('executionFee' in value) || value['executionFee'] === undefined) return false;
    if (!('layerzeroFee' in value) || value['layerzeroFee'] === undefined) return false;
    if (!('protocolFee' in value) || value['protocolFee'] === undefined) return false;
    if (!('solverFee' in value) || value['solverFee'] === undefined) return false;
    return true;
}

export function GatewayOnrampFeeBreakdownFromJSON(json: any): GatewayOnrampFeeBreakdown {
    return GatewayOnrampFeeBreakdownFromJSONTyped(json, false);
}

export function GatewayOnrampFeeBreakdownFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): GatewayOnrampFeeBreakdown {
    if (json == null) {
        return json;
    }
    return {
        affiliateFee: json['affiliateFee'],
        executionFee: json['executionFee'],
        layerzeroFee: json['layerzeroFee'],
        protocolFee: json['protocolFee'],
        solverFee: json['solverFee'],
    };
}

export function GatewayOnrampFeeBreakdownToJSON(json: any): GatewayOnrampFeeBreakdown {
    return GatewayOnrampFeeBreakdownToJSONTyped(json, false);
}

export function GatewayOnrampFeeBreakdownToJSONTyped(
    value?: GatewayOnrampFeeBreakdown | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        affiliateFee: value['affiliateFee'],
        executionFee: value['executionFee'],
        layerzeroFee: value['layerzeroFee'],
        protocolFee: value['protocolFee'],
        solverFee: value['solverFee'],
    };
}
