/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenSwapAffiliateV3 } from './TokenSwapAffiliateV3';
import {
    TokenSwapAffiliateV3FromJSON,
    TokenSwapAffiliateV3FromJSONTyped,
    TokenSwapAffiliateV3ToJSON,
    TokenSwapAffiliateV3ToJSONTyped,
} from './TokenSwapAffiliateV3';
import type { GatewayTokenAmountV2 } from './GatewayTokenAmountV2';
import {
    GatewayTokenAmountV2FromJSON,
    GatewayTokenAmountV2FromJSONTyped,
    GatewayTokenAmountV2ToJSON,
    GatewayTokenAmountV2ToJSONTyped,
} from './GatewayTokenAmountV2';

/**
 * V4 token-swap quote with its source-chain refund address.
 * @export
 * @interface GatewayTokenSwapQuoteV4
 */
export interface GatewayTokenSwapQuoteV4 {
    /**
     * 
     * @type {string}
     * @memberof GatewayTokenSwapQuoteV4
     */
    dstChain: string;
    /**
     * Estimated time in secs to complete the Order
     * @type {number}
     * @memberof GatewayTokenSwapQuoteV4
     */
    estimatedTimeInSecs: number;
    /**
     * 
     * @type {GatewayTokenAmountV2}
     * @memberof GatewayTokenSwapQuoteV4
     */
    fees: GatewayTokenAmountV2;
    /**
     * 
     * @type {GatewayTokenAmountV2}
     * @memberof GatewayTokenSwapQuoteV4
     */
    inputAmount: GatewayTokenAmountV2;
    /**
     * 
     * @type {GatewayTokenAmountV2}
     * @memberof GatewayTokenSwapQuoteV4
     */
    outputAmount: GatewayTokenAmountV2;
    /**
     * Price impact as a fraction, e.g. `"-0.05"` means 5% loss. Absent if no price feed is
     * available.
     * @type {string}
     * @memberof GatewayTokenSwapQuoteV4
     */
    priceImpact?: string;
    /**
     * Price impact in USD, excluding execution fee. E.g. `"-1.00"` means $1 loss. Absent if no
     * price feed is available.
     * @type {string}
     * @memberof GatewayTokenSwapQuoteV4
     */
    priceImpactUsd?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayTokenSwapQuoteV4
     */
    recipient: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayTokenSwapQuoteV4
     */
    sender?: string;
    /**
     * 
     * @type {number}
     * @memberof GatewayTokenSwapQuoteV4
     */
    slippage: number;
    /**
     * 
     * @type {string}
     * @memberof GatewayTokenSwapQuoteV4
     */
    srcChain: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayTokenSwapQuoteV4
     */
    txTo: string;
    /**
     * 
     * @type {TokenSwapAffiliateV3}
     * @memberof GatewayTokenSwapQuoteV4
     */
    affiliate?: TokenSwapAffiliateV3 | null;
    /**
     * Source-chain address used for refunds; required by create-order
     * @type {string}
     * @memberof GatewayTokenSwapQuoteV4
     */
    refundAddress?: string | null;
}

/**
 * Check if a given object implements the GatewayTokenSwapQuoteV4 interface.
 */
export function instanceOfGatewayTokenSwapQuoteV4(value: object): value is GatewayTokenSwapQuoteV4 {
    if (!('dstChain' in value) || value['dstChain'] === undefined) return false;
    if (!('estimatedTimeInSecs' in value) || value['estimatedTimeInSecs'] === undefined) return false;
    if (!('fees' in value) || value['fees'] === undefined) return false;
    if (!('inputAmount' in value) || value['inputAmount'] === undefined) return false;
    if (!('outputAmount' in value) || value['outputAmount'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('slippage' in value) || value['slippage'] === undefined) return false;
    if (!('srcChain' in value) || value['srcChain'] === undefined) return false;
    if (!('txTo' in value) || value['txTo'] === undefined) return false;
    return true;
}

export function GatewayTokenSwapQuoteV4FromJSON(json: any): GatewayTokenSwapQuoteV4 {
    return GatewayTokenSwapQuoteV4FromJSONTyped(json, false);
}

export function GatewayTokenSwapQuoteV4FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayTokenSwapQuoteV4 {
    if (json == null) {
        return json;
    }
    return {
        
        'dstChain': json['dstChain'],
        'estimatedTimeInSecs': json['estimatedTimeInSecs'],
        'fees': GatewayTokenAmountV2FromJSON(json['fees']),
        'inputAmount': GatewayTokenAmountV2FromJSON(json['inputAmount']),
        'outputAmount': GatewayTokenAmountV2FromJSON(json['outputAmount']),
        'priceImpact': json['priceImpact'] == null ? undefined : json['priceImpact'],
        'priceImpactUsd': json['priceImpactUsd'] == null ? undefined : json['priceImpactUsd'],
        'recipient': json['recipient'],
        'sender': json['sender'] == null ? undefined : json['sender'],
        'slippage': json['slippage'],
        'srcChain': json['srcChain'],
        'txTo': json['txTo'],
        'affiliate': json['affiliate'] == null ? undefined : TokenSwapAffiliateV3FromJSON(json['affiliate']),
        'refundAddress': json['refundAddress'] == null ? undefined : json['refundAddress'],
    };
}

export function GatewayTokenSwapQuoteV4ToJSON(json: any): GatewayTokenSwapQuoteV4 {
    return GatewayTokenSwapQuoteV4ToJSONTyped(json, false);
}

export function GatewayTokenSwapQuoteV4ToJSONTyped(value?: GatewayTokenSwapQuoteV4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dstChain': value['dstChain'],
        'estimatedTimeInSecs': value['estimatedTimeInSecs'],
        'fees': GatewayTokenAmountV2ToJSON(value['fees']),
        'inputAmount': GatewayTokenAmountV2ToJSON(value['inputAmount']),
        'outputAmount': GatewayTokenAmountV2ToJSON(value['outputAmount']),
        'priceImpact': value['priceImpact'],
        'priceImpactUsd': value['priceImpactUsd'],
        'recipient': value['recipient'],
        'sender': value['sender'],
        'slippage': value['slippage'],
        'srcChain': value['srcChain'],
        'txTo': value['txTo'],
        'affiliate': TokenSwapAffiliateV3ToJSON(value['affiliate']),
        'refundAddress': value['refundAddress'],
    };
}

