/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayErrorDetailsOneOf
 */
export interface GatewayErrorDetailsOneOf {
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsOneOf
     */
    actual: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsOneOf
     */
    expected: string;
}

/**
 * Check if a given object implements the GatewayErrorDetailsOneOf interface.
 */
export function instanceOfGatewayErrorDetailsOneOf(value: object): value is GatewayErrorDetailsOneOf {
    if (!('actual' in value) || value['actual'] === undefined) return false;
    if (!('expected' in value) || value['expected'] === undefined) return false;
    return true;
}

export function GatewayErrorDetailsOneOfFromJSON(json: any): GatewayErrorDetailsOneOf {
    return GatewayErrorDetailsOneOfFromJSONTyped(json, false);
}

export function GatewayErrorDetailsOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorDetailsOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'actual': json['actual'],
        'expected': json['expected'],
    };
}

export function GatewayErrorDetailsOneOfToJSON(json: any): GatewayErrorDetailsOneOf {
    return GatewayErrorDetailsOneOfToJSONTyped(json, false);
}

export function GatewayErrorDetailsOneOfToJSONTyped(value?: GatewayErrorDetailsOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actual': value['actual'],
        'expected': value['expected'],
    };
}

