/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayOrderStatusOneOfInProgress } from './GatewayOrderStatusOneOfInProgress';
import {
    GatewayOrderStatusOneOfInProgressFromJSON,
    GatewayOrderStatusOneOfInProgressFromJSONTyped,
    GatewayOrderStatusOneOfInProgressToJSON,
    GatewayOrderStatusOneOfInProgressToJSONTyped,
} from './GatewayOrderStatusOneOfInProgress';

/**
 * 
 * @export
 * @interface GatewayOrderStatusOneOf
 */
export interface GatewayOrderStatusOneOf {
    /**
     * 
     * @type {GatewayOrderStatusOneOfInProgress}
     * @memberof GatewayOrderStatusOneOf
     */
    inProgress: GatewayOrderStatusOneOfInProgress;
}

/**
 * Check if a given object implements the GatewayOrderStatusOneOf interface.
 */
export function instanceOfGatewayOrderStatusOneOf(value: object): value is GatewayOrderStatusOneOf {
    if (!('inProgress' in value) || value['inProgress'] === undefined) return false;
    return true;
}

export function GatewayOrderStatusOneOfFromJSON(json: any): GatewayOrderStatusOneOf {
    return GatewayOrderStatusOneOfFromJSONTyped(json, false);
}

export function GatewayOrderStatusOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderStatusOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'inProgress': GatewayOrderStatusOneOfInProgressFromJSON(json['inProgress']),
    };
}

export function GatewayOrderStatusOneOfToJSON(json: any): GatewayOrderStatusOneOf {
    return GatewayOrderStatusOneOfToJSONTyped(json, false);
}

export function GatewayOrderStatusOneOfToJSONTyped(value?: GatewayOrderStatusOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inProgress': GatewayOrderStatusOneOfInProgressToJSON(value['inProgress']),
    };
}

