/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayErrorDetailsV2OneOf6
 */
export interface GatewayErrorDetailsV2OneOf6 {
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsV2OneOf6
     */
    actual: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsV2OneOf6
     */
    minimum: string;
}

/**
 * Check if a given object implements the GatewayErrorDetailsV2OneOf6 interface.
 */
export function instanceOfGatewayErrorDetailsV2OneOf6(value: object): value is GatewayErrorDetailsV2OneOf6 {
    if (!('actual' in value) || value['actual'] === undefined) return false;
    if (!('minimum' in value) || value['minimum'] === undefined) return false;
    return true;
}

export function GatewayErrorDetailsV2OneOf6FromJSON(json: any): GatewayErrorDetailsV2OneOf6 {
    return GatewayErrorDetailsV2OneOf6FromJSONTyped(json, false);
}

export function GatewayErrorDetailsV2OneOf6FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorDetailsV2OneOf6 {
    if (json == null) {
        return json;
    }
    return {
        
        'actual': json['actual'],
        'minimum': json['minimum'],
    };
}

export function GatewayErrorDetailsV2OneOf6ToJSON(json: any): GatewayErrorDetailsV2OneOf6 {
    return GatewayErrorDetailsV2OneOf6ToJSONTyped(json, false);
}

export function GatewayErrorDetailsV2OneOf6ToJSONTyped(value?: GatewayErrorDetailsV2OneOf6 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actual': value['actual'],
        'minimum': value['minimum'],
    };
}

