/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * New error codes for V2.
 * @export
 */
export const GatewayErrorCodeV2Variants = {
    InvalidCursor: 'INVALID_CURSOR'
} as const;
export type GatewayErrorCodeV2Variants = typeof GatewayErrorCodeV2Variants[keyof typeof GatewayErrorCodeV2Variants];


export function instanceOfGatewayErrorCodeV2Variants(value: any): boolean {
    for (const key in GatewayErrorCodeV2Variants) {
        if (Object.prototype.hasOwnProperty.call(GatewayErrorCodeV2Variants, key)) {
            if (GatewayErrorCodeV2Variants[key as keyof typeof GatewayErrorCodeV2Variants] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GatewayErrorCodeV2VariantsFromJSON(json: any): GatewayErrorCodeV2Variants {
    return GatewayErrorCodeV2VariantsFromJSONTyped(json, false);
}

export function GatewayErrorCodeV2VariantsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorCodeV2Variants {
    return json as GatewayErrorCodeV2Variants;
}

export function GatewayErrorCodeV2VariantsToJSON(value?: GatewayErrorCodeV2Variants | null): any {
    return value as any;
}

export function GatewayErrorCodeV2VariantsToJSONTyped(value: any, ignoreDiscriminator: boolean): GatewayErrorCodeV2Variants {
    return value as GatewayErrorCodeV2Variants;
}

