/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TxInfo } from './TxInfo';
import {
    TxInfoFromJSON,
    TxInfoFromJSONTyped,
    TxInfoToJSON,
    TxInfoToJSONTyped,
} from './TxInfo';
import type { GatewayTokenAmount } from './GatewayTokenAmount';
import {
    GatewayTokenAmountFromJSON,
    GatewayTokenAmountFromJSONTyped,
    GatewayTokenAmountToJSON,
    GatewayTokenAmountToJSONTyped,
} from './GatewayTokenAmount';

/**
 * 
 * @export
 * @interface GatewayLayerZeroQuote
 */
export interface GatewayLayerZeroQuote {
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayLayerZeroQuote
     */
    fees: GatewayTokenAmount;
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayLayerZeroQuote
     */
    inputAmount: GatewayTokenAmount;
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayLayerZeroQuote
     */
    outputAmount: GatewayTokenAmount;
    /**
     * 
     * @type {TxInfo}
     * @memberof GatewayLayerZeroQuote
     */
    tx: TxInfo;
}

/**
 * Check if a given object implements the GatewayLayerZeroQuote interface.
 */
export function instanceOfGatewayLayerZeroQuote(value: object): value is GatewayLayerZeroQuote {
    if (!('fees' in value) || value['fees'] === undefined) return false;
    if (!('inputAmount' in value) || value['inputAmount'] === undefined) return false;
    if (!('outputAmount' in value) || value['outputAmount'] === undefined) return false;
    if (!('tx' in value) || value['tx'] === undefined) return false;
    return true;
}

export function GatewayLayerZeroQuoteFromJSON(json: any): GatewayLayerZeroQuote {
    return GatewayLayerZeroQuoteFromJSONTyped(json, false);
}

export function GatewayLayerZeroQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayLayerZeroQuote {
    if (json == null) {
        return json;
    }
    return {
        
        'fees': GatewayTokenAmountFromJSON(json['fees']),
        'inputAmount': GatewayTokenAmountFromJSON(json['inputAmount']),
        'outputAmount': GatewayTokenAmountFromJSON(json['outputAmount']),
        'tx': TxInfoFromJSON(json['tx']),
    };
}

export function GatewayLayerZeroQuoteToJSON(json: any): GatewayLayerZeroQuote {
    return GatewayLayerZeroQuoteToJSONTyped(json, false);
}

export function GatewayLayerZeroQuoteToJSONTyped(value?: GatewayLayerZeroQuote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fees': GatewayTokenAmountToJSON(value['fees']),
        'inputAmount': GatewayTokenAmountToJSON(value['inputAmount']),
        'outputAmount': GatewayTokenAmountToJSON(value['outputAmount']),
        'tx': TxInfoToJSON(value['tx']),
    };
}

