/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GatewayTxDataOneOf } from './GatewayTxDataOneOf';
import {
    instanceOfGatewayTxDataOneOf,
    GatewayTxDataOneOfFromJSON,
    GatewayTxDataOneOfFromJSONTyped,
    GatewayTxDataOneOfToJSON,
} from './GatewayTxDataOneOf';
import type { GatewayTxDataOneOf1 } from './GatewayTxDataOneOf1';
import {
    instanceOfGatewayTxDataOneOf1,
    GatewayTxDataOneOf1FromJSON,
    GatewayTxDataOneOf1FromJSONTyped,
    GatewayTxDataOneOf1ToJSON,
} from './GatewayTxDataOneOf1';
import type { GatewayTxDataOneOf2 } from './GatewayTxDataOneOf2';
import {
    instanceOfGatewayTxDataOneOf2,
    GatewayTxDataOneOf2FromJSON,
    GatewayTxDataOneOf2FromJSONTyped,
    GatewayTxDataOneOf2ToJSON,
} from './GatewayTxDataOneOf2';

/**
 * @type GatewayTxData
 * Tagged union of EVM, Tron and Solana transaction data for V3 create-order responses.
 * @export
 */
export type GatewayTxData = GatewayTxDataOneOf | GatewayTxDataOneOf1 | GatewayTxDataOneOf2;

export function GatewayTxDataFromJSON(json: any): GatewayTxData {
    return GatewayTxDataFromJSONTyped(json, false);
}

export function GatewayTxDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayTxData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGatewayTxDataOneOf(json)) {
        return GatewayTxDataOneOfFromJSONTyped(json, true);
    }
    if (instanceOfGatewayTxDataOneOf1(json)) {
        return GatewayTxDataOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfGatewayTxDataOneOf2(json)) {
        return GatewayTxDataOneOf2FromJSONTyped(json, true);
    }
    return {} as any;
}

export function GatewayTxDataToJSON(json: any): any {
    return GatewayTxDataToJSONTyped(json, false);
}

export function GatewayTxDataToJSONTyped(value?: GatewayTxData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGatewayTxDataOneOf(value)) {
        return GatewayTxDataOneOfToJSON(value as GatewayTxDataOneOf);
    }
    if (instanceOfGatewayTxDataOneOf1(value)) {
        return GatewayTxDataOneOf1ToJSON(value as GatewayTxDataOneOf1);
    }
    if (instanceOfGatewayTxDataOneOf2(value)) {
        return GatewayTxDataOneOf2ToJSON(value as GatewayTxDataOneOf2);
    }
    return {};
}

