/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayErrorDetailsV2OneOf1
 */
export interface GatewayErrorDetailsV2OneOf1 {
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsV2OneOf1
     */
    available: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsV2OneOf1
     */
    required: string;
}

/**
 * Check if a given object implements the GatewayErrorDetailsV2OneOf1 interface.
 */
export function instanceOfGatewayErrorDetailsV2OneOf1(value: object): value is GatewayErrorDetailsV2OneOf1 {
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('required' in value) || value['required'] === undefined) return false;
    return true;
}

export function GatewayErrorDetailsV2OneOf1FromJSON(json: any): GatewayErrorDetailsV2OneOf1 {
    return GatewayErrorDetailsV2OneOf1FromJSONTyped(json, false);
}

export function GatewayErrorDetailsV2OneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorDetailsV2OneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'],
        'required': json['required'],
    };
}

export function GatewayErrorDetailsV2OneOf1ToJSON(json: any): GatewayErrorDetailsV2OneOf1 {
    return GatewayErrorDetailsV2OneOf1ToJSONTyped(json, false);
}

export function GatewayErrorDetailsV2OneOf1ToJSONTyped(value?: GatewayErrorDetailsV2OneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': value['available'],
        'required': value['required'],
    };
}

