/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayCreateOrderV3OneOf1Offramp } from './GatewayCreateOrderV3OneOf1Offramp';
import {
    GatewayCreateOrderV3OneOf1OfframpFromJSON,
    GatewayCreateOrderV3OneOf1OfframpFromJSONTyped,
    GatewayCreateOrderV3OneOf1OfframpToJSON,
    GatewayCreateOrderV3OneOf1OfframpToJSONTyped,
} from './GatewayCreateOrderV3OneOf1Offramp';

/**
 * 
 * @export
 * @interface GatewayCreateOrderV3OneOf1
 */
export interface GatewayCreateOrderV3OneOf1 {
    /**
     * 
     * @type {GatewayCreateOrderV3OneOf1Offramp}
     * @memberof GatewayCreateOrderV3OneOf1
     */
    offramp: GatewayCreateOrderV3OneOf1Offramp;
}

/**
 * Check if a given object implements the GatewayCreateOrderV3OneOf1 interface.
 */
export function instanceOfGatewayCreateOrderV3OneOf1(value: object): value is GatewayCreateOrderV3OneOf1 {
    if (!('offramp' in value) || value['offramp'] === undefined) return false;
    return true;
}

export function GatewayCreateOrderV3OneOf1FromJSON(json: any): GatewayCreateOrderV3OneOf1 {
    return GatewayCreateOrderV3OneOf1FromJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayCreateOrderV3OneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'offramp': GatewayCreateOrderV3OneOf1OfframpFromJSON(json['offramp']),
    };
}

export function GatewayCreateOrderV3OneOf1ToJSON(json: any): GatewayCreateOrderV3OneOf1 {
    return GatewayCreateOrderV3OneOf1ToJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOf1ToJSONTyped(value?: GatewayCreateOrderV3OneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offramp': GatewayCreateOrderV3OneOf1OfframpToJSON(value['offramp']),
    };
}

