/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayCreateOrderV3OneOf1Offramp } from './GatewayCreateOrderV3OneOf1Offramp';
import {
    GatewayCreateOrderV3OneOf1OfframpFromJSON,
    GatewayCreateOrderV3OneOf1OfframpFromJSONTyped,
    GatewayCreateOrderV3OneOf1OfframpToJSON,
    GatewayCreateOrderV3OneOf1OfframpToJSONTyped,
} from './GatewayCreateOrderV3OneOf1Offramp';

/**
 * 
 * @export
 * @interface GatewayCreateOrderV3OneOf2
 */
export interface GatewayCreateOrderV3OneOf2 {
    /**
     * 
     * @type {GatewayCreateOrderV3OneOf1Offramp}
     * @memberof GatewayCreateOrderV3OneOf2
     */
    tokenSwap: GatewayCreateOrderV3OneOf1Offramp;
}

/**
 * Check if a given object implements the GatewayCreateOrderV3OneOf2 interface.
 */
export function instanceOfGatewayCreateOrderV3OneOf2(value: object): value is GatewayCreateOrderV3OneOf2 {
    if (!('tokenSwap' in value) || value['tokenSwap'] === undefined) return false;
    return true;
}

export function GatewayCreateOrderV3OneOf2FromJSON(json: any): GatewayCreateOrderV3OneOf2 {
    return GatewayCreateOrderV3OneOf2FromJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayCreateOrderV3OneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenSwap': GatewayCreateOrderV3OneOf1OfframpFromJSON(json['tokenSwap']),
    };
}

export function GatewayCreateOrderV3OneOf2ToJSON(json: any): GatewayCreateOrderV3OneOf2 {
    return GatewayCreateOrderV3OneOf2ToJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOf2ToJSONTyped(value?: GatewayCreateOrderV3OneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokenSwap': GatewayCreateOrderV3OneOf1OfframpToJSON(value['tokenSwap']),
    };
}

