/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TxInfo } from './TxInfo';
import {
    TxInfoFromJSON,
    TxInfoFromJSONTyped,
    TxInfoToJSON,
    TxInfoToJSONTyped,
} from './TxInfo';

/**
 * 
 * @export
 * @interface GatewayOrderStatusV3OneOf1Failed
 */
export interface GatewayOrderStatusV3OneOf1Failed {
    /**
     * 
     * @type {TxInfo}
     * @memberof GatewayOrderStatusV3OneOf1Failed
     */
    refundTx?: TxInfo | null;
}

/**
 * Check if a given object implements the GatewayOrderStatusV3OneOf1Failed interface.
 */
export function instanceOfGatewayOrderStatusV3OneOf1Failed(value: object): value is GatewayOrderStatusV3OneOf1Failed {
    return true;
}

export function GatewayOrderStatusV3OneOf1FailedFromJSON(json: any): GatewayOrderStatusV3OneOf1Failed {
    return GatewayOrderStatusV3OneOf1FailedFromJSONTyped(json, false);
}

export function GatewayOrderStatusV3OneOf1FailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderStatusV3OneOf1Failed {
    if (json == null) {
        return json;
    }
    return {
        
        'refundTx': json['refund_tx'] == null ? undefined : TxInfoFromJSON(json['refund_tx']),
    };
}

export function GatewayOrderStatusV3OneOf1FailedToJSON(json: any): GatewayOrderStatusV3OneOf1Failed {
    return GatewayOrderStatusV3OneOf1FailedToJSONTyped(json, false);
}

export function GatewayOrderStatusV3OneOf1FailedToJSONTyped(value?: GatewayOrderStatusV3OneOf1Failed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refund_tx': TxInfoToJSON(value['refundTx']),
    };
}

