/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayOrderStatusV2OneOfInProgress } from './GatewayOrderStatusV2OneOfInProgress';
import {
    GatewayOrderStatusV2OneOfInProgressFromJSON,
    GatewayOrderStatusV2OneOfInProgressFromJSONTyped,
    GatewayOrderStatusV2OneOfInProgressToJSON,
    GatewayOrderStatusV2OneOfInProgressToJSONTyped,
} from './GatewayOrderStatusV2OneOfInProgress';

/**
 * 
 * @export
 * @interface GatewayOrderStatusV2OneOf
 */
export interface GatewayOrderStatusV2OneOf {
    /**
     * 
     * @type {GatewayOrderStatusV2OneOfInProgress}
     * @memberof GatewayOrderStatusV2OneOf
     */
    inProgress: GatewayOrderStatusV2OneOfInProgress;
}

/**
 * Check if a given object implements the GatewayOrderStatusV2OneOf interface.
 */
export function instanceOfGatewayOrderStatusV2OneOf(value: object): value is GatewayOrderStatusV2OneOf {
    if (!('inProgress' in value) || value['inProgress'] === undefined) return false;
    return true;
}

export function GatewayOrderStatusV2OneOfFromJSON(json: any): GatewayOrderStatusV2OneOf {
    return GatewayOrderStatusV2OneOfFromJSONTyped(json, false);
}

export function GatewayOrderStatusV2OneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderStatusV2OneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'inProgress': GatewayOrderStatusV2OneOfInProgressFromJSON(json['inProgress']),
    };
}

export function GatewayOrderStatusV2OneOfToJSON(json: any): GatewayOrderStatusV2OneOf {
    return GatewayOrderStatusV2OneOfToJSONTyped(json, false);
}

export function GatewayOrderStatusV2OneOfToJSONTyped(value?: GatewayOrderStatusV2OneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inProgress': GatewayOrderStatusV2OneOfInProgressToJSON(value['inProgress']),
    };
}

