/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayOfframpFeeBreakdown
 */
export interface GatewayOfframpFeeBreakdown {
    /**
     * 
     * @type {string}
     * @memberof GatewayOfframpFeeBreakdown
     */
    affiliateFee: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayOfframpFeeBreakdown
     */
    fastestFeeRate: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayOfframpFeeBreakdown
     */
    inclusionFee: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayOfframpFeeBreakdown
     */
    protocolFee: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayOfframpFeeBreakdown
     */
    solverFee: string;
}

/**
 * Check if a given object implements the GatewayOfframpFeeBreakdown interface.
 */
export function instanceOfGatewayOfframpFeeBreakdown(value: object): value is GatewayOfframpFeeBreakdown {
    if (!('affiliateFee' in value) || value['affiliateFee'] === undefined) return false;
    if (!('fastestFeeRate' in value) || value['fastestFeeRate'] === undefined) return false;
    if (!('inclusionFee' in value) || value['inclusionFee'] === undefined) return false;
    if (!('protocolFee' in value) || value['protocolFee'] === undefined) return false;
    if (!('solverFee' in value) || value['solverFee'] === undefined) return false;
    return true;
}

export function GatewayOfframpFeeBreakdownFromJSON(json: any): GatewayOfframpFeeBreakdown {
    return GatewayOfframpFeeBreakdownFromJSONTyped(json, false);
}

export function GatewayOfframpFeeBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOfframpFeeBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'affiliateFee': json['affiliateFee'],
        'fastestFeeRate': json['fastestFeeRate'],
        'inclusionFee': json['inclusionFee'],
        'protocolFee': json['protocolFee'],
        'solverFee': json['solverFee'],
    };
}

export function GatewayOfframpFeeBreakdownToJSON(json: any): GatewayOfframpFeeBreakdown {
    return GatewayOfframpFeeBreakdownToJSONTyped(json, false);
}

export function GatewayOfframpFeeBreakdownToJSONTyped(value?: GatewayOfframpFeeBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affiliateFee': value['affiliateFee'],
        'fastestFeeRate': value['fastestFeeRate'],
        'inclusionFee': value['inclusionFee'],
        'protocolFee': value['protocolFee'],
        'solverFee': value['solverFee'],
    };
}

