/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayErrorDetailsV3OneOf1
 */
export interface GatewayErrorDetailsV3OneOf1 {
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsV3OneOf1
     */
    actual: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsV3OneOf1
     */
    max: string;
}

/**
 * Check if a given object implements the GatewayErrorDetailsV3OneOf1 interface.
 */
export function instanceOfGatewayErrorDetailsV3OneOf1(value: object): value is GatewayErrorDetailsV3OneOf1 {
    if (!('actual' in value) || value['actual'] === undefined) return false;
    if (!('max' in value) || value['max'] === undefined) return false;
    return true;
}

export function GatewayErrorDetailsV3OneOf1FromJSON(json: any): GatewayErrorDetailsV3OneOf1 {
    return GatewayErrorDetailsV3OneOf1FromJSONTyped(json, false);
}

export function GatewayErrorDetailsV3OneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorDetailsV3OneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'actual': json['actual'],
        'max': json['max'],
    };
}

export function GatewayErrorDetailsV3OneOf1ToJSON(json: any): GatewayErrorDetailsV3OneOf1 {
    return GatewayErrorDetailsV3OneOf1ToJSONTyped(json, false);
}

export function GatewayErrorDetailsV3OneOf1ToJSONTyped(value?: GatewayErrorDetailsV3OneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actual': value['actual'],
        'max': value['max'],
    };
}

