/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayTxData } from './GatewayTxData';
import {
    GatewayTxDataFromJSON,
    GatewayTxDataFromJSONTyped,
    GatewayTxDataToJSON,
    GatewayTxDataToJSONTyped,
} from './GatewayTxData';

/**
 * 
 * @export
 * @interface GatewayCreateOrderV3OneOfOfframp
 */
export interface GatewayCreateOrderV3OneOfOfframp {
    /**
     * Unique order id
     * @type {string}
     * @memberof GatewayCreateOrderV3OneOfOfframp
     */
    orderId: string;
    /**
     * Tx data to execute the swap (EVM or Solana)
     * @type {GatewayTxData}
     * @memberof GatewayCreateOrderV3OneOfOfframp
     */
    tx: GatewayTxData;
}

/**
 * Check if a given object implements the GatewayCreateOrderV3OneOfOfframp interface.
 */
export function instanceOfGatewayCreateOrderV3OneOfOfframp(value: object): value is GatewayCreateOrderV3OneOfOfframp {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('tx' in value) || value['tx'] === undefined) return false;
    return true;
}

export function GatewayCreateOrderV3OneOfOfframpFromJSON(json: any): GatewayCreateOrderV3OneOfOfframp {
    return GatewayCreateOrderV3OneOfOfframpFromJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOfOfframpFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayCreateOrderV3OneOfOfframp {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['order_id'],
        'tx': GatewayTxDataFromJSON(json['tx']),
    };
}

export function GatewayCreateOrderV3OneOfOfframpToJSON(json: any): GatewayCreateOrderV3OneOfOfframp {
    return GatewayCreateOrderV3OneOfOfframpToJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOfOfframpToJSONTyped(value?: GatewayCreateOrderV3OneOfOfframp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_id': value['orderId'],
        'tx': GatewayTxDataToJSON(value['tx']),
    };
}

