/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GatewayQuoteV2OneOf } from './GatewayQuoteV2OneOf';
import {
    instanceOfGatewayQuoteV2OneOf,
    GatewayQuoteV2OneOfFromJSON,
    GatewayQuoteV2OneOfFromJSONTyped,
    GatewayQuoteV2OneOfToJSON,
} from './GatewayQuoteV2OneOf';
import type { GatewayQuoteV3OneOf } from './GatewayQuoteV3OneOf';
import {
    instanceOfGatewayQuoteV3OneOf,
    GatewayQuoteV3OneOfFromJSON,
    GatewayQuoteV3OneOfFromJSONTyped,
    GatewayQuoteV3OneOfToJSON,
} from './GatewayQuoteV3OneOf';
import type { GatewayQuoteV3OneOf1 } from './GatewayQuoteV3OneOf1';
import {
    instanceOfGatewayQuoteV3OneOf1,
    GatewayQuoteV3OneOf1FromJSON,
    GatewayQuoteV3OneOf1FromJSONTyped,
    GatewayQuoteV3OneOf1ToJSON,
} from './GatewayQuoteV3OneOf1';

/**
 * @type GatewayQuoteV3
 * V3 gateway quote — used for both the get-quote response and the create-order body.
 * `ownerAddress` is embedded in each variant that carries an owner concept.
 * @export
 */
export type GatewayQuoteV3 = GatewayQuoteV2OneOf | GatewayQuoteV3OneOf | GatewayQuoteV3OneOf1;

export function GatewayQuoteV3FromJSON(json: any): GatewayQuoteV3 {
    return GatewayQuoteV3FromJSONTyped(json, false);
}

export function GatewayQuoteV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayQuoteV3 {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGatewayQuoteV2OneOf(json)) {
        return GatewayQuoteV2OneOfFromJSONTyped(json, true);
    }
    if (instanceOfGatewayQuoteV3OneOf(json)) {
        return GatewayQuoteV3OneOfFromJSONTyped(json, true);
    }
    if (instanceOfGatewayQuoteV3OneOf1(json)) {
        return GatewayQuoteV3OneOf1FromJSONTyped(json, true);
    }
    return {} as any;
}

export function GatewayQuoteV3ToJSON(json: any): any {
    return GatewayQuoteV3ToJSONTyped(json, false);
}

export function GatewayQuoteV3ToJSONTyped(value?: GatewayQuoteV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGatewayQuoteV2OneOf(value)) {
        return GatewayQuoteV2OneOfToJSON(value as GatewayQuoteV2OneOf);
    }
    if (instanceOfGatewayQuoteV3OneOf(value)) {
        return GatewayQuoteV3OneOfToJSON(value as GatewayQuoteV3OneOf);
    }
    if (instanceOfGatewayQuoteV3OneOf1(value)) {
        return GatewayQuoteV3OneOf1ToJSON(value as GatewayQuoteV3OneOf1);
    }
    return {};
}

