/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GatewayErrorDetailsOneOf } from './GatewayErrorDetailsOneOf';
import {
    instanceOfGatewayErrorDetailsOneOf,
    GatewayErrorDetailsOneOfFromJSON,
    GatewayErrorDetailsOneOfFromJSONTyped,
    GatewayErrorDetailsOneOfToJSON,
} from './GatewayErrorDetailsOneOf';
import type { GatewayErrorDetailsOneOf1 } from './GatewayErrorDetailsOneOf1';
import {
    instanceOfGatewayErrorDetailsOneOf1,
    GatewayErrorDetailsOneOf1FromJSON,
    GatewayErrorDetailsOneOf1FromJSONTyped,
    GatewayErrorDetailsOneOf1ToJSON,
} from './GatewayErrorDetailsOneOf1';
import type { GatewayErrorDetailsOneOf2 } from './GatewayErrorDetailsOneOf2';
import {
    instanceOfGatewayErrorDetailsOneOf2,
    GatewayErrorDetailsOneOf2FromJSON,
    GatewayErrorDetailsOneOf2FromJSONTyped,
    GatewayErrorDetailsOneOf2ToJSON,
} from './GatewayErrorDetailsOneOf2';
import type { GatewayErrorDetailsOneOf3 } from './GatewayErrorDetailsOneOf3';
import {
    instanceOfGatewayErrorDetailsOneOf3,
    GatewayErrorDetailsOneOf3FromJSON,
    GatewayErrorDetailsOneOf3FromJSONTyped,
    GatewayErrorDetailsOneOf3ToJSON,
} from './GatewayErrorDetailsOneOf3';
import type { GatewayErrorDetailsOneOf4 } from './GatewayErrorDetailsOneOf4';
import {
    instanceOfGatewayErrorDetailsOneOf4,
    GatewayErrorDetailsOneOf4FromJSON,
    GatewayErrorDetailsOneOf4FromJSONTyped,
    GatewayErrorDetailsOneOf4ToJSON,
} from './GatewayErrorDetailsOneOf4';
import type { GatewayErrorDetailsOneOf5 } from './GatewayErrorDetailsOneOf5';
import {
    instanceOfGatewayErrorDetailsOneOf5,
    GatewayErrorDetailsOneOf5FromJSON,
    GatewayErrorDetailsOneOf5FromJSONTyped,
    GatewayErrorDetailsOneOf5ToJSON,
} from './GatewayErrorDetailsOneOf5';
import type { GatewayErrorDetailsOneOf6 } from './GatewayErrorDetailsOneOf6';
import {
    instanceOfGatewayErrorDetailsOneOf6,
    GatewayErrorDetailsOneOf6FromJSON,
    GatewayErrorDetailsOneOf6FromJSONTyped,
    GatewayErrorDetailsOneOf6ToJSON,
} from './GatewayErrorDetailsOneOf6';
import type { GatewayErrorDetailsV2OneOf } from './GatewayErrorDetailsV2OneOf';
import {
    instanceOfGatewayErrorDetailsV2OneOf,
    GatewayErrorDetailsV2OneOfFromJSON,
    GatewayErrorDetailsV2OneOfFromJSONTyped,
    GatewayErrorDetailsV2OneOfToJSON,
} from './GatewayErrorDetailsV2OneOf';

/**
 * @type GatewayErrorDetailsV2
 * Structured details for V2 error types - all V1 variants plus V2-only ones.
 * 
 * Kept as a single flat `oneOf` (not nested under V1/V2 wrappers) so OpenAPI clients
 * (e.g. typescript-fetch) can generate type guards correctly.
 * @export
 */
export type GatewayErrorDetailsV2 = GatewayErrorDetailsOneOf | GatewayErrorDetailsOneOf1 | GatewayErrorDetailsOneOf2 | GatewayErrorDetailsOneOf3 | GatewayErrorDetailsOneOf4 | GatewayErrorDetailsOneOf5 | GatewayErrorDetailsOneOf6 | GatewayErrorDetailsV2OneOf;

export function GatewayErrorDetailsV2FromJSON(json: any): GatewayErrorDetailsV2 {
    return GatewayErrorDetailsV2FromJSONTyped(json, false);
}

export function GatewayErrorDetailsV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorDetailsV2 {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGatewayErrorDetailsOneOf(json)) {
        return GatewayErrorDetailsOneOfFromJSONTyped(json, true);
    }
    if (instanceOfGatewayErrorDetailsOneOf1(json)) {
        return GatewayErrorDetailsOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfGatewayErrorDetailsOneOf2(json)) {
        return GatewayErrorDetailsOneOf2FromJSONTyped(json, true);
    }
    if (instanceOfGatewayErrorDetailsOneOf3(json)) {
        return GatewayErrorDetailsOneOf3FromJSONTyped(json, true);
    }
    if (instanceOfGatewayErrorDetailsOneOf4(json)) {
        return GatewayErrorDetailsOneOf4FromJSONTyped(json, true);
    }
    if (instanceOfGatewayErrorDetailsOneOf5(json)) {
        return GatewayErrorDetailsOneOf5FromJSONTyped(json, true);
    }
    if (instanceOfGatewayErrorDetailsOneOf6(json)) {
        return GatewayErrorDetailsOneOf6FromJSONTyped(json, true);
    }
    if (instanceOfGatewayErrorDetailsV2OneOf(json)) {
        return GatewayErrorDetailsV2OneOfFromJSONTyped(json, true);
    }
    return {} as any;
}

export function GatewayErrorDetailsV2ToJSON(json: any): any {
    return GatewayErrorDetailsV2ToJSONTyped(json, false);
}

export function GatewayErrorDetailsV2ToJSONTyped(value?: GatewayErrorDetailsV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGatewayErrorDetailsOneOf(value)) {
        return GatewayErrorDetailsOneOfToJSON(value as GatewayErrorDetailsOneOf);
    }
    if (instanceOfGatewayErrorDetailsOneOf1(value)) {
        return GatewayErrorDetailsOneOf1ToJSON(value as GatewayErrorDetailsOneOf1);
    }
    if (instanceOfGatewayErrorDetailsOneOf2(value)) {
        return GatewayErrorDetailsOneOf2ToJSON(value as GatewayErrorDetailsOneOf2);
    }
    if (instanceOfGatewayErrorDetailsOneOf3(value)) {
        return GatewayErrorDetailsOneOf3ToJSON(value as GatewayErrorDetailsOneOf3);
    }
    if (instanceOfGatewayErrorDetailsOneOf4(value)) {
        return GatewayErrorDetailsOneOf4ToJSON(value as GatewayErrorDetailsOneOf4);
    }
    if (instanceOfGatewayErrorDetailsOneOf5(value)) {
        return GatewayErrorDetailsOneOf5ToJSON(value as GatewayErrorDetailsOneOf5);
    }
    if (instanceOfGatewayErrorDetailsOneOf6(value)) {
        return GatewayErrorDetailsOneOf6ToJSON(value as GatewayErrorDetailsOneOf6);
    }
    if (instanceOfGatewayErrorDetailsV2OneOf(value)) {
        return GatewayErrorDetailsV2OneOfToJSON(value as GatewayErrorDetailsV2OneOf);
    }
    return {};
}

