/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayTokenAmount } from './GatewayTokenAmount';
import {
    GatewayTokenAmountFromJSON,
    GatewayTokenAmountFromJSONTyped,
    GatewayTokenAmountToJSON,
    GatewayTokenAmountToJSONTyped,
} from './GatewayTokenAmount';

/**
 * 
 * @export
 * @interface GatewayOnrampFeeBreakdown
 */
export interface GatewayOnrampFeeBreakdown {
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayOnrampFeeBreakdown
     */
    affiliateFee: GatewayTokenAmount;
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayOnrampFeeBreakdown
     */
    executionFee: GatewayTokenAmount;
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayOnrampFeeBreakdown
     */
    layerzeroFee: GatewayTokenAmount;
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayOnrampFeeBreakdown
     */
    protocolFee: GatewayTokenAmount;
    /**
     * 
     * @type {GatewayTokenAmount}
     * @memberof GatewayOnrampFeeBreakdown
     */
    solverFee: GatewayTokenAmount;
}

/**
 * Check if a given object implements the GatewayOnrampFeeBreakdown interface.
 */
export function instanceOfGatewayOnrampFeeBreakdown(value: object): value is GatewayOnrampFeeBreakdown {
    if (!('affiliateFee' in value) || value['affiliateFee'] === undefined) return false;
    if (!('executionFee' in value) || value['executionFee'] === undefined) return false;
    if (!('layerzeroFee' in value) || value['layerzeroFee'] === undefined) return false;
    if (!('protocolFee' in value) || value['protocolFee'] === undefined) return false;
    if (!('solverFee' in value) || value['solverFee'] === undefined) return false;
    return true;
}

export function GatewayOnrampFeeBreakdownFromJSON(json: any): GatewayOnrampFeeBreakdown {
    return GatewayOnrampFeeBreakdownFromJSONTyped(json, false);
}

export function GatewayOnrampFeeBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOnrampFeeBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'affiliateFee': GatewayTokenAmountFromJSON(json['affiliateFee']),
        'executionFee': GatewayTokenAmountFromJSON(json['executionFee']),
        'layerzeroFee': GatewayTokenAmountFromJSON(json['layerzeroFee']),
        'protocolFee': GatewayTokenAmountFromJSON(json['protocolFee']),
        'solverFee': GatewayTokenAmountFromJSON(json['solverFee']),
    };
}

export function GatewayOnrampFeeBreakdownToJSON(json: any): GatewayOnrampFeeBreakdown {
    return GatewayOnrampFeeBreakdownToJSONTyped(json, false);
}

export function GatewayOnrampFeeBreakdownToJSONTyped(value?: GatewayOnrampFeeBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affiliateFee': GatewayTokenAmountToJSON(value['affiliateFee']),
        'executionFee': GatewayTokenAmountToJSON(value['executionFee']),
        'layerzeroFee': GatewayTokenAmountToJSON(value['layerzeroFee']),
        'protocolFee': GatewayTokenAmountToJSON(value['protocolFee']),
        'solverFee': GatewayTokenAmountToJSON(value['solverFee']),
    };
}

