/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayCreateOrderOneOf1Offramp } from './GatewayCreateOrderOneOf1Offramp';
import {
    GatewayCreateOrderOneOf1OfframpFromJSON,
    GatewayCreateOrderOneOf1OfframpFromJSONTyped,
    GatewayCreateOrderOneOf1OfframpToJSON,
    GatewayCreateOrderOneOf1OfframpToJSONTyped,
} from './GatewayCreateOrderOneOf1Offramp';

/**
 * 
 * @export
 * @interface GatewayCreateOrderOneOf1
 */
export interface GatewayCreateOrderOneOf1 {
    /**
     * 
     * @type {GatewayCreateOrderOneOf1Offramp}
     * @memberof GatewayCreateOrderOneOf1
     */
    offramp: GatewayCreateOrderOneOf1Offramp;
}

/**
 * Check if a given object implements the GatewayCreateOrderOneOf1 interface.
 */
export function instanceOfGatewayCreateOrderOneOf1(value: object): value is GatewayCreateOrderOneOf1 {
    if (!('offramp' in value) || value['offramp'] === undefined) return false;
    return true;
}

export function GatewayCreateOrderOneOf1FromJSON(json: any): GatewayCreateOrderOneOf1 {
    return GatewayCreateOrderOneOf1FromJSONTyped(json, false);
}

export function GatewayCreateOrderOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayCreateOrderOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'offramp': GatewayCreateOrderOneOf1OfframpFromJSON(json['offramp']),
    };
}

export function GatewayCreateOrderOneOf1ToJSON(json: any): GatewayCreateOrderOneOf1 {
    return GatewayCreateOrderOneOf1ToJSONTyped(json, false);
}

export function GatewayCreateOrderOneOf1ToJSONTyped(value?: GatewayCreateOrderOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offramp': GatewayCreateOrderOneOf1OfframpToJSON(value['offramp']),
    };
}

