/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayTokenSwapQuoteV2 } from './GatewayTokenSwapQuoteV2';
import {
    GatewayTokenSwapQuoteV2FromJSON,
    GatewayTokenSwapQuoteV2FromJSONTyped,
    GatewayTokenSwapQuoteV2ToJSON,
    GatewayTokenSwapQuoteV2ToJSONTyped,
} from './GatewayTokenSwapQuoteV2';

/**
 * 
 * @export
 * @interface GatewayQuoteV2OneOf2
 */
export interface GatewayQuoteV2OneOf2 {
    /**
     * 
     * @type {GatewayTokenSwapQuoteV2}
     * @memberof GatewayQuoteV2OneOf2
     */
    tokenSwap: GatewayTokenSwapQuoteV2;
}

/**
 * Check if a given object implements the GatewayQuoteV2OneOf2 interface.
 */
export function instanceOfGatewayQuoteV2OneOf2(value: object): value is GatewayQuoteV2OneOf2 {
    if (!('tokenSwap' in value) || value['tokenSwap'] === undefined) return false;
    return true;
}

export function GatewayQuoteV2OneOf2FromJSON(json: any): GatewayQuoteV2OneOf2 {
    return GatewayQuoteV2OneOf2FromJSONTyped(json, false);
}

export function GatewayQuoteV2OneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayQuoteV2OneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenSwap': GatewayTokenSwapQuoteV2FromJSON(json['tokenSwap']),
    };
}

export function GatewayQuoteV2OneOf2ToJSON(json: any): GatewayQuoteV2OneOf2 {
    return GatewayQuoteV2OneOf2ToJSONTyped(json, false);
}

export function GatewayQuoteV2OneOf2ToJSONTyped(value?: GatewayQuoteV2OneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokenSwap': GatewayTokenSwapQuoteV2ToJSON(value['tokenSwap']),
    };
}

