/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayErrorDetailsV2OneOf
 */
export interface GatewayErrorDetailsV2OneOf {
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsV2OneOf
     */
    actual: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsV2OneOf
     */
    expected: string;
}

/**
 * Check if a given object implements the GatewayErrorDetailsV2OneOf interface.
 */
export function instanceOfGatewayErrorDetailsV2OneOf(value: object): value is GatewayErrorDetailsV2OneOf {
    if (!('actual' in value) || value['actual'] === undefined) return false;
    if (!('expected' in value) || value['expected'] === undefined) return false;
    return true;
}

export function GatewayErrorDetailsV2OneOfFromJSON(json: any): GatewayErrorDetailsV2OneOf {
    return GatewayErrorDetailsV2OneOfFromJSONTyped(json, false);
}

export function GatewayErrorDetailsV2OneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorDetailsV2OneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'actual': json['actual'],
        'expected': json['expected'],
    };
}

export function GatewayErrorDetailsV2OneOfToJSON(json: any): GatewayErrorDetailsV2OneOf {
    return GatewayErrorDetailsV2OneOfToJSONTyped(json, false);
}

export function GatewayErrorDetailsV2OneOfToJSONTyped(value?: GatewayErrorDetailsV2OneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actual': value['actual'],
        'expected': value['expected'],
    };
}

