/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayOrderStatusV3OneOf3Refunded } from './GatewayOrderStatusV3OneOf3Refunded';
import {
    GatewayOrderStatusV3OneOf3RefundedFromJSON,
    GatewayOrderStatusV3OneOf3RefundedFromJSONTyped,
    GatewayOrderStatusV3OneOf3RefundedToJSON,
    GatewayOrderStatusV3OneOf3RefundedToJSONTyped,
} from './GatewayOrderStatusV3OneOf3Refunded';

/**
 * 
 * @export
 * @interface GatewayOrderStatusV3OneOf3
 */
export interface GatewayOrderStatusV3OneOf3 {
    /**
     * 
     * @type {GatewayOrderStatusV3OneOf3Refunded}
     * @memberof GatewayOrderStatusV3OneOf3
     */
    refunded: GatewayOrderStatusV3OneOf3Refunded;
}

/**
 * Check if a given object implements the GatewayOrderStatusV3OneOf3 interface.
 */
export function instanceOfGatewayOrderStatusV3OneOf3(value: object): value is GatewayOrderStatusV3OneOf3 {
    if (!('refunded' in value) || value['refunded'] === undefined) return false;
    return true;
}

export function GatewayOrderStatusV3OneOf3FromJSON(json: any): GatewayOrderStatusV3OneOf3 {
    return GatewayOrderStatusV3OneOf3FromJSONTyped(json, false);
}

export function GatewayOrderStatusV3OneOf3FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderStatusV3OneOf3 {
    if (json == null) {
        return json;
    }
    return {
        
        'refunded': GatewayOrderStatusV3OneOf3RefundedFromJSON(json['refunded']),
    };
}

export function GatewayOrderStatusV3OneOf3ToJSON(json: any): GatewayOrderStatusV3OneOf3 {
    return GatewayOrderStatusV3OneOf3ToJSONTyped(json, false);
}

export function GatewayOrderStatusV3OneOf3ToJSONTyped(value?: GatewayOrderStatusV3OneOf3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refunded': GatewayOrderStatusV3OneOf3RefundedToJSON(value['refunded']),
    };
}

