/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayOfframpQuoteV2 } from './GatewayOfframpQuoteV2';
import {
    GatewayOfframpQuoteV2FromJSON,
    GatewayOfframpQuoteV2FromJSONTyped,
    GatewayOfframpQuoteV2ToJSON,
    GatewayOfframpQuoteV2ToJSONTyped,
} from './GatewayOfframpQuoteV2';

/**
 * 
 * @export
 * @interface GatewayQuoteV2OneOf1
 */
export interface GatewayQuoteV2OneOf1 {
    /**
     * 
     * @type {GatewayOfframpQuoteV2}
     * @memberof GatewayQuoteV2OneOf1
     */
    offramp: GatewayOfframpQuoteV2;
}

/**
 * Check if a given object implements the GatewayQuoteV2OneOf1 interface.
 */
export function instanceOfGatewayQuoteV2OneOf1(value: object): value is GatewayQuoteV2OneOf1 {
    if (!('offramp' in value) || value['offramp'] === undefined) return false;
    return true;
}

export function GatewayQuoteV2OneOf1FromJSON(json: any): GatewayQuoteV2OneOf1 {
    return GatewayQuoteV2OneOf1FromJSONTyped(json, false);
}

export function GatewayQuoteV2OneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayQuoteV2OneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'offramp': GatewayOfframpQuoteV2FromJSON(json['offramp']),
    };
}

export function GatewayQuoteV2OneOf1ToJSON(json: any): GatewayQuoteV2OneOf1 {
    return GatewayQuoteV2OneOf1ToJSONTyped(json, false);
}

export function GatewayQuoteV2OneOf1ToJSONTyped(value?: GatewayQuoteV2OneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offramp': GatewayOfframpQuoteV2ToJSON(value['offramp']),
    };
}

