/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayErrorCodeV2 } from './GatewayErrorCodeV2';
import {
    GatewayErrorCodeV2FromJSON,
    GatewayErrorCodeV2FromJSONTyped,
    GatewayErrorCodeV2ToJSON,
    GatewayErrorCodeV2ToJSONTyped,
} from './GatewayErrorCodeV2';
import type { GatewayErrorDetailsV2 } from './GatewayErrorDetailsV2';
import {
    GatewayErrorDetailsV2FromJSON,
    GatewayErrorDetailsV2FromJSONTyped,
    GatewayErrorDetailsV2ToJSON,
    GatewayErrorDetailsV2ToJSONTyped,
} from './GatewayErrorDetailsV2';

/**
 * Structured error response for V2 API.
 * Contains an error code, human-readable message, and optional structured details.
 * @export
 * @interface GatewayErrorV2
 */
export interface GatewayErrorV2 {
    /**
     * Stable error code for frontend parsing
     * @type {GatewayErrorCodeV2}
     * @memberof GatewayErrorV2
     */
    code: GatewayErrorCodeV2;
    /**
     * Optional structured details specific to the error type
     * @type {GatewayErrorDetailsV2}
     * @memberof GatewayErrorV2
     */
    details?: GatewayErrorDetailsV2 | null;
    /**
     * Human-readable error message
     * @type {string}
     * @memberof GatewayErrorV2
     */
    error: string;
}

/**
 * Check if a given object implements the GatewayErrorV2 interface.
 */
export function instanceOfGatewayErrorV2(value: object): value is GatewayErrorV2 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GatewayErrorV2FromJSON(json: any): GatewayErrorV2 {
    return GatewayErrorV2FromJSONTyped(json, false);
}

export function GatewayErrorV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': GatewayErrorCodeV2FromJSON(json['code']),
        'details': json['details'] == null ? undefined : GatewayErrorDetailsV2FromJSON(json['details']),
        'error': json['error'],
    };
}

export function GatewayErrorV2ToJSON(json: any): GatewayErrorV2 {
    return GatewayErrorV2ToJSONTyped(json, false);
}

export function GatewayErrorV2ToJSONTyped(value?: GatewayErrorV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': GatewayErrorCodeV2ToJSON(value['code']),
        'details': GatewayErrorDetailsV2ToJSON(value['details']),
        'error': value['error'],
    };
}

