/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TxInfo } from './TxInfo';
import {
    TxInfoFromJSON,
    TxInfoFromJSONTyped,
    TxInfoToJSON,
    TxInfoToJSONTyped,
} from './TxInfo';

/**
 * 
 * @export
 * @interface GatewayOrderStatusOneOfInProgress
 */
export interface GatewayOrderStatusOneOfInProgress {
    /**
     * 
     * @type {TxInfo}
     * @memberof GatewayOrderStatusOneOfInProgress
     */
    bumpFeeTx?: TxInfo | null;
    /**
     * 
     * @type {TxInfo}
     * @memberof GatewayOrderStatusOneOfInProgress
     */
    refundTx?: TxInfo | null;
}

/**
 * Check if a given object implements the GatewayOrderStatusOneOfInProgress interface.
 */
export function instanceOfGatewayOrderStatusOneOfInProgress(value: object): value is GatewayOrderStatusOneOfInProgress {
    return true;
}

export function GatewayOrderStatusOneOfInProgressFromJSON(json: any): GatewayOrderStatusOneOfInProgress {
    return GatewayOrderStatusOneOfInProgressFromJSONTyped(json, false);
}

export function GatewayOrderStatusOneOfInProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderStatusOneOfInProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'bumpFeeTx': json['bump_fee_tx'] == null ? undefined : TxInfoFromJSON(json['bump_fee_tx']),
        'refundTx': json['refund_tx'] == null ? undefined : TxInfoFromJSON(json['refund_tx']),
    };
}

export function GatewayOrderStatusOneOfInProgressToJSON(json: any): GatewayOrderStatusOneOfInProgress {
    return GatewayOrderStatusOneOfInProgressToJSONTyped(json, false);
}

export function GatewayOrderStatusOneOfInProgressToJSONTyped(value?: GatewayOrderStatusOneOfInProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bump_fee_tx': TxInfoToJSON(value['bumpFeeTx']),
        'refund_tx': TxInfoToJSON(value['refundTx']),
    };
}

