/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayUserTokenTransferV3 } from './GatewayUserTokenTransferV3';
import {
    GatewayUserTokenTransferV3FromJSON,
    GatewayUserTokenTransferV3FromJSONTyped,
    GatewayUserTokenTransferV3ToJSON,
    GatewayUserTokenTransferV3ToJSONTyped,
} from './GatewayUserTokenTransferV3';

/**
 * 
 * @export
 * @interface GatewayOrderStatusV3OneOf3Refunded
 */
export interface GatewayOrderStatusV3OneOf3Refunded {
    /**
     * 
     * @type {Array<GatewayUserTokenTransferV3>}
     * @memberof GatewayOrderStatusV3OneOf3Refunded
     */
    refundedTokens: Array<GatewayUserTokenTransferV3>;
}

/**
 * Check if a given object implements the GatewayOrderStatusV3OneOf3Refunded interface.
 */
export function instanceOfGatewayOrderStatusV3OneOf3Refunded(value: object): value is GatewayOrderStatusV3OneOf3Refunded {
    if (!('refundedTokens' in value) || value['refundedTokens'] === undefined) return false;
    return true;
}

export function GatewayOrderStatusV3OneOf3RefundedFromJSON(json: any): GatewayOrderStatusV3OneOf3Refunded {
    return GatewayOrderStatusV3OneOf3RefundedFromJSONTyped(json, false);
}

export function GatewayOrderStatusV3OneOf3RefundedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderStatusV3OneOf3Refunded {
    if (json == null) {
        return json;
    }
    return {
        
        'refundedTokens': ((json['refunded_tokens'] as Array<any>).map(GatewayUserTokenTransferV3FromJSON)),
    };
}

export function GatewayOrderStatusV3OneOf3RefundedToJSON(json: any): GatewayOrderStatusV3OneOf3Refunded {
    return GatewayOrderStatusV3OneOf3RefundedToJSONTyped(json, false);
}

export function GatewayOrderStatusV3OneOf3RefundedToJSONTyped(value?: GatewayOrderStatusV3OneOf3Refunded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refunded_tokens': ((value['refundedTokens'] as Array<any>).map(GatewayUserTokenTransferV3ToJSON)),
    };
}

