/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayOrderStatusV3OneOf1Failed } from './GatewayOrderStatusV3OneOf1Failed';
import {
    GatewayOrderStatusV3OneOf1FailedFromJSON,
    GatewayOrderStatusV3OneOf1FailedFromJSONTyped,
    GatewayOrderStatusV3OneOf1FailedToJSON,
    GatewayOrderStatusV3OneOf1FailedToJSONTyped,
} from './GatewayOrderStatusV3OneOf1Failed';

/**
 * 
 * @export
 * @interface GatewayOrderStatusV3OneOf1
 */
export interface GatewayOrderStatusV3OneOf1 {
    /**
     * 
     * @type {GatewayOrderStatusV3OneOf1Failed}
     * @memberof GatewayOrderStatusV3OneOf1
     */
    failed: GatewayOrderStatusV3OneOf1Failed;
}

/**
 * Check if a given object implements the GatewayOrderStatusV3OneOf1 interface.
 */
export function instanceOfGatewayOrderStatusV3OneOf1(value: object): value is GatewayOrderStatusV3OneOf1 {
    if (!('failed' in value) || value['failed'] === undefined) return false;
    return true;
}

export function GatewayOrderStatusV3OneOf1FromJSON(json: any): GatewayOrderStatusV3OneOf1 {
    return GatewayOrderStatusV3OneOf1FromJSONTyped(json, false);
}

export function GatewayOrderStatusV3OneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderStatusV3OneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'failed': GatewayOrderStatusV3OneOf1FailedFromJSON(json['failed']),
    };
}

export function GatewayOrderStatusV3OneOf1ToJSON(json: any): GatewayOrderStatusV3OneOf1 {
    return GatewayOrderStatusV3OneOf1ToJSONTyped(json, false);
}

export function GatewayOrderStatusV3OneOf1ToJSONTyped(value?: GatewayOrderStatusV3OneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failed': GatewayOrderStatusV3OneOf1FailedToJSON(value['failed']),
    };
}

