/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayCreateOrderOneOf1Offramp } from './GatewayCreateOrderOneOf1Offramp';
import {
    GatewayCreateOrderOneOf1OfframpFromJSON,
    GatewayCreateOrderOneOf1OfframpFromJSONTyped,
    GatewayCreateOrderOneOf1OfframpToJSON,
    GatewayCreateOrderOneOf1OfframpToJSONTyped,
} from './GatewayCreateOrderOneOf1Offramp';

/**
 * 
 * @export
 * @interface GatewayCreateOrderOneOf2
 */
export interface GatewayCreateOrderOneOf2 {
    /**
     * 
     * @type {GatewayCreateOrderOneOf1Offramp}
     * @memberof GatewayCreateOrderOneOf2
     */
    layerZero: GatewayCreateOrderOneOf1Offramp;
}

/**
 * Check if a given object implements the GatewayCreateOrderOneOf2 interface.
 */
export function instanceOfGatewayCreateOrderOneOf2(value: object): value is GatewayCreateOrderOneOf2 {
    if (!('layerZero' in value) || value['layerZero'] === undefined) return false;
    return true;
}

export function GatewayCreateOrderOneOf2FromJSON(json: any): GatewayCreateOrderOneOf2 {
    return GatewayCreateOrderOneOf2FromJSONTyped(json, false);
}

export function GatewayCreateOrderOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayCreateOrderOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'layerZero': GatewayCreateOrderOneOf1OfframpFromJSON(json['layerZero']),
    };
}

export function GatewayCreateOrderOneOf2ToJSON(json: any): GatewayCreateOrderOneOf2 {
    return GatewayCreateOrderOneOf2ToJSONTyped(json, false);
}

export function GatewayCreateOrderOneOf2ToJSONTyped(value?: GatewayCreateOrderOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'layerZero': GatewayCreateOrderOneOf1OfframpToJSON(value['layerZero']),
    };
}

