/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayCreateOrderV3OneOfOfframp } from './GatewayCreateOrderV3OneOfOfframp';
import {
    GatewayCreateOrderV3OneOfOfframpFromJSON,
    GatewayCreateOrderV3OneOfOfframpFromJSONTyped,
    GatewayCreateOrderV3OneOfOfframpToJSON,
    GatewayCreateOrderV3OneOfOfframpToJSONTyped,
} from './GatewayCreateOrderV3OneOfOfframp';

/**
 * 
 * @export
 * @interface GatewayCreateOrderV3OneOf1
 */
export interface GatewayCreateOrderV3OneOf1 {
    /**
     * 
     * @type {GatewayCreateOrderV3OneOfOfframp}
     * @memberof GatewayCreateOrderV3OneOf1
     */
    tokenSwap: GatewayCreateOrderV3OneOfOfframp;
}

/**
 * Check if a given object implements the GatewayCreateOrderV3OneOf1 interface.
 */
export function instanceOfGatewayCreateOrderV3OneOf1(value: object): value is GatewayCreateOrderV3OneOf1 {
    if (!('tokenSwap' in value) || value['tokenSwap'] === undefined) return false;
    return true;
}

export function GatewayCreateOrderV3OneOf1FromJSON(json: any): GatewayCreateOrderV3OneOf1 {
    return GatewayCreateOrderV3OneOf1FromJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayCreateOrderV3OneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenSwap': GatewayCreateOrderV3OneOfOfframpFromJSON(json['tokenSwap']),
    };
}

export function GatewayCreateOrderV3OneOf1ToJSON(json: any): GatewayCreateOrderV3OneOf1 {
    return GatewayCreateOrderV3OneOf1ToJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOf1ToJSONTyped(value?: GatewayCreateOrderV3OneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokenSwap': GatewayCreateOrderV3OneOfOfframpToJSON(value['tokenSwap']),
    };
}

