/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GatewayTokenSwapQuoteV4 } from './GatewayTokenSwapQuoteV4';
import {
    GatewayTokenSwapQuoteV4FromJSON,
    GatewayTokenSwapQuoteV4FromJSONTyped,
    GatewayTokenSwapQuoteV4ToJSON,
    GatewayTokenSwapQuoteV4ToJSONTyped,
} from './GatewayTokenSwapQuoteV4';

/**
 * 
 * @export
 * @interface GatewayQuoteV4OneOf1
 */
export interface GatewayQuoteV4OneOf1 {
    /**
     * 
     * @type {GatewayTokenSwapQuoteV4}
     * @memberof GatewayQuoteV4OneOf1
     */
    tokenSwap: GatewayTokenSwapQuoteV4;
}

/**
 * Check if a given object implements the GatewayQuoteV4OneOf1 interface.
 */
export function instanceOfGatewayQuoteV4OneOf1(value: object): value is GatewayQuoteV4OneOf1 {
    if (!('tokenSwap' in value) || value['tokenSwap'] === undefined) return false;
    return true;
}

export function GatewayQuoteV4OneOf1FromJSON(json: any): GatewayQuoteV4OneOf1 {
    return GatewayQuoteV4OneOf1FromJSONTyped(json, false);
}

export function GatewayQuoteV4OneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayQuoteV4OneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenSwap': GatewayTokenSwapQuoteV4FromJSON(json['tokenSwap']),
    };
}

export function GatewayQuoteV4OneOf1ToJSON(json: any): GatewayQuoteV4OneOf1 {
    return GatewayQuoteV4OneOf1ToJSONTyped(json, false);
}

export function GatewayQuoteV4OneOf1ToJSONTyped(value?: GatewayQuoteV4OneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokenSwap': GatewayTokenSwapQuoteV4ToJSON(value['tokenSwap']),
    };
}

