/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayErrorDetailsOneOf2
 */
export interface GatewayErrorDetailsOneOf2 {
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsOneOf2
     */
    availableAmount: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayErrorDetailsOneOf2
     */
    totalFees: string;
}

/**
 * Check if a given object implements the GatewayErrorDetailsOneOf2 interface.
 */
export function instanceOfGatewayErrorDetailsOneOf2(value: object): value is GatewayErrorDetailsOneOf2 {
    if (!('availableAmount' in value) || value['availableAmount'] === undefined) return false;
    if (!('totalFees' in value) || value['totalFees'] === undefined) return false;
    return true;
}

export function GatewayErrorDetailsOneOf2FromJSON(json: any): GatewayErrorDetailsOneOf2 {
    return GatewayErrorDetailsOneOf2FromJSONTyped(json, false);
}

export function GatewayErrorDetailsOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayErrorDetailsOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'availableAmount': json['available_amount'],
        'totalFees': json['total_fees'],
    };
}

export function GatewayErrorDetailsOneOf2ToJSON(json: any): GatewayErrorDetailsOneOf2 {
    return GatewayErrorDetailsOneOf2ToJSONTyped(json, false);
}

export function GatewayErrorDetailsOneOf2ToJSONTyped(value?: GatewayErrorDetailsOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available_amount': value['availableAmount'],
        'total_fees': value['totalFees'],
    };
}

