/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GatewayCreateOrderV3OneOfOnramp
 */
export interface GatewayCreateOrderV3OneOfOnramp {
    /**
     * Bitcoin address to pay to
     * @type {string}
     * @memberof GatewayCreateOrderV3OneOfOnramp
     */
    address: string;
    /**
     * Optional OP_RETURN data
     * @type {string}
     * @memberof GatewayCreateOrderV3OneOfOnramp
     */
    opReturnData?: string | null;
    /**
     * Unique order id
     * @type {string}
     * @memberof GatewayCreateOrderV3OneOfOnramp
     */
    orderId: string;
    /**
     * Hex-encoded Bitcoin PSBT (only present when sender address was provided).
     * 
     * Coin selection does NOT detect or exclude ordinals, inscriptions, or runes. If the
     * sender address holds such assets, the PSBT may spend those UTXOs as ordinary sats.
     * Callers holding ordinal-bearing UTXOs should fund the order from a separate address.
     * @type {string}
     * @memberof GatewayCreateOrderV3OneOfOnramp
     */
    psbtHex?: string | null;
}

/**
 * Check if a given object implements the GatewayCreateOrderV3OneOfOnramp interface.
 */
export function instanceOfGatewayCreateOrderV3OneOfOnramp(value: object): value is GatewayCreateOrderV3OneOfOnramp {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    return true;
}

export function GatewayCreateOrderV3OneOfOnrampFromJSON(json: any): GatewayCreateOrderV3OneOfOnramp {
    return GatewayCreateOrderV3OneOfOnrampFromJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOfOnrampFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayCreateOrderV3OneOfOnramp {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'opReturnData': json['op_return_data'] == null ? undefined : json['op_return_data'],
        'orderId': json['order_id'],
        'psbtHex': json['psbt_hex'] == null ? undefined : json['psbt_hex'],
    };
}

export function GatewayCreateOrderV3OneOfOnrampToJSON(json: any): GatewayCreateOrderV3OneOfOnramp {
    return GatewayCreateOrderV3OneOfOnrampToJSONTyped(json, false);
}

export function GatewayCreateOrderV3OneOfOnrampToJSONTyped(value?: GatewayCreateOrderV3OneOfOnramp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'op_return_data': value['opReturnData'],
        'order_id': value['orderId'],
        'psbt_hex': value['psbtHex'],
    };
}

