/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const OnrampStatus = {
    BtcConfirmation: 'btc-confirmation',
    L2Processing: 'l2-processing',
    L2Incomplete: 'l2-incomplete',
    L2Confirmation: 'l2-confirmation',
} as const;
export type OnrampStatus = (typeof OnrampStatus)[keyof typeof OnrampStatus];

export function instanceOfOnrampStatus(value: any): boolean {
    for (const key in OnrampStatus) {
        if (Object.prototype.hasOwnProperty.call(OnrampStatus, key)) {
            if (OnrampStatus[key as keyof typeof OnrampStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OnrampStatusFromJSON(json: any): OnrampStatus {
    return OnrampStatusFromJSONTyped(json, false);
}

export function OnrampStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnrampStatus {
    return json as OnrampStatus;
}

export function OnrampStatusToJSON(value?: OnrampStatus | null): any {
    return value as any;
}

export function OnrampStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): OnrampStatus {
    return value as OnrampStatus;
}
