/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderDestinationInfo
 */
export interface OrderDestinationInfo {
    /**
     * The _estimated_ amount of the output token, as determined by initial create-order
     * @type {string}
     * @memberof OrderDestinationInfo
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDestinationInfo
     */
    chain: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDestinationInfo
     */
    token: string;
}

/**
 * Check if a given object implements the OrderDestinationInfo interface.
 */
export function instanceOfOrderDestinationInfo(value: object): value is OrderDestinationInfo {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function OrderDestinationInfoFromJSON(json: any): OrderDestinationInfo {
    return OrderDestinationInfoFromJSONTyped(json, false);
}

export function OrderDestinationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDestinationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'chain': json['chain'],
        'token': json['token'],
    };
}

export function OrderDestinationInfoToJSON(json: any): OrderDestinationInfo {
    return OrderDestinationInfoToJSONTyped(json, false);
}

export function OrderDestinationInfoToJSONTyped(value?: OrderDestinationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'chain': value['chain'],
        'token': value['token'],
    };
}

