/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pending BTC payment (v3) — adds `usd`.
 * @export
 * @interface PendingBtcPaymentV3
 */
export interface PendingBtcPaymentV3 {
    /**
     * 
     * @type {string}
     * @memberof PendingBtcPaymentV3
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof PendingBtcPaymentV3
     */
    txid: string;
    /**
     * USD value of the pending BTC amount, derived from the order's input rate.
     * @type {string}
     * @memberof PendingBtcPaymentV3
     */
    usd?: string | null;
}

/**
 * Check if a given object implements the PendingBtcPaymentV3 interface.
 */
export function instanceOfPendingBtcPaymentV3(value: object): value is PendingBtcPaymentV3 {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('txid' in value) || value['txid'] === undefined) return false;
    return true;
}

export function PendingBtcPaymentV3FromJSON(json: any): PendingBtcPaymentV3 {
    return PendingBtcPaymentV3FromJSONTyped(json, false);
}

export function PendingBtcPaymentV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingBtcPaymentV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'txid': json['txid'],
        'usd': json['usd'] == null ? undefined : json['usd'],
    };
}

export function PendingBtcPaymentV3ToJSON(json: any): PendingBtcPaymentV3 {
    return PendingBtcPaymentV3ToJSONTyped(json, false);
}

export function PendingBtcPaymentV3ToJSONTyped(value?: PendingBtcPaymentV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'txid': value['txid'],
        'usd': value['usd'],
    };
}

