/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RegisterTxOneOf } from './RegisterTxOneOf';
import {
    instanceOfRegisterTxOneOf,
    RegisterTxOneOfFromJSON,
    RegisterTxOneOfFromJSONTyped,
    RegisterTxOneOfToJSON,
} from './RegisterTxOneOf';
import type { RegisterTxOneOf1 } from './RegisterTxOneOf1';
import {
    instanceOfRegisterTxOneOf1,
    RegisterTxOneOf1FromJSON,
    RegisterTxOneOf1FromJSONTyped,
    RegisterTxOneOf1ToJSON,
} from './RegisterTxOneOf1';
import type { RegisterTxOneOf2 } from './RegisterTxOneOf2';
import {
    instanceOfRegisterTxOneOf2,
    RegisterTxOneOf2FromJSON,
    RegisterTxOneOf2FromJSONTyped,
    RegisterTxOneOf2ToJSON,
} from './RegisterTxOneOf2';

/**
 * @type RegisterTx
 * Gateway order to execute
 * @export
 */
export type RegisterTx = RegisterTxOneOf | RegisterTxOneOf1 | RegisterTxOneOf2;

export function RegisterTxFromJSON(json: any): RegisterTx {
    return RegisterTxFromJSONTyped(json, false);
}

export function RegisterTxFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterTx {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfRegisterTxOneOf(json)) {
        return RegisterTxOneOfFromJSONTyped(json, true);
    }
    if (instanceOfRegisterTxOneOf1(json)) {
        return RegisterTxOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfRegisterTxOneOf2(json)) {
        return RegisterTxOneOf2FromJSONTyped(json, true);
    }
    return {} as any;
}

export function RegisterTxToJSON(json: any): any {
    return RegisterTxToJSONTyped(json, false);
}

export function RegisterTxToJSONTyped(value?: RegisterTx | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfRegisterTxOneOf(value)) {
        return RegisterTxOneOfToJSON(value as RegisterTxOneOf);
    }
    if (instanceOfRegisterTxOneOf1(value)) {
        return RegisterTxOneOf1ToJSON(value as RegisterTxOneOf1);
    }
    if (instanceOfRegisterTxOneOf2(value)) {
        return RegisterTxOneOf2ToJSON(value as RegisterTxOneOf2);
    }
    return {};
}

