/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterTxSuccessOneOfOnramp
 */
export interface RegisterTxSuccessOneOfOnramp {
    /**
     * 
     * @type {string}
     * @memberof RegisterTxSuccessOneOfOnramp
     */
    txid: string;
}

/**
 * Check if a given object implements the RegisterTxSuccessOneOfOnramp interface.
 */
export function instanceOfRegisterTxSuccessOneOfOnramp(value: object): value is RegisterTxSuccessOneOfOnramp {
    if (!('txid' in value) || value['txid'] === undefined) return false;
    return true;
}

export function RegisterTxSuccessOneOfOnrampFromJSON(json: any): RegisterTxSuccessOneOfOnramp {
    return RegisterTxSuccessOneOfOnrampFromJSONTyped(json, false);
}

export function RegisterTxSuccessOneOfOnrampFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterTxSuccessOneOfOnramp {
    if (json == null) {
        return json;
    }
    return {
        
        'txid': json['txid'],
    };
}

export function RegisterTxSuccessOneOfOnrampToJSON(json: any): RegisterTxSuccessOneOfOnramp {
    return RegisterTxSuccessOneOfOnrampToJSONTyped(json, false);
}

export function RegisterTxSuccessOneOfOnrampToJSONTyped(value?: RegisterTxSuccessOneOfOnramp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'txid': value['txid'],
    };
}

