/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegisterTxOneOfOnramp } from './RegisterTxOneOfOnramp';
import {
    RegisterTxOneOfOnrampFromJSON,
    RegisterTxOneOfOnrampFromJSONTyped,
    RegisterTxOneOfOnrampToJSON,
    RegisterTxOneOfOnrampToJSONTyped,
} from './RegisterTxOneOfOnramp';

/**
 * 
 * @export
 * @interface RegisterTxOneOf
 */
export interface RegisterTxOneOf {
    /**
     * 
     * @type {RegisterTxOneOfOnramp}
     * @memberof RegisterTxOneOf
     */
    onramp: RegisterTxOneOfOnramp;
}

/**
 * Check if a given object implements the RegisterTxOneOf interface.
 */
export function instanceOfRegisterTxOneOf(value: object): value is RegisterTxOneOf {
    if (!('onramp' in value) || value['onramp'] === undefined) return false;
    return true;
}

export function RegisterTxOneOfFromJSON(json: any): RegisterTxOneOf {
    return RegisterTxOneOfFromJSONTyped(json, false);
}

export function RegisterTxOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterTxOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'onramp': RegisterTxOneOfOnrampFromJSON(json['onramp']),
    };
}

export function RegisterTxOneOfToJSON(json: any): RegisterTxOneOf {
    return RegisterTxOneOfToJSONTyped(json, false);
}

export function RegisterTxOneOfToJSONTyped(value?: RegisterTxOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'onramp': RegisterTxOneOfOnrampToJSON(value['onramp']),
    };
}

