/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterTxOneOf1Offramp
 */
export interface RegisterTxOneOf1Offramp {
    /**
     * EVM txhash
     * @type {string}
     * @memberof RegisterTxOneOf1Offramp
     */
    evmTxhash: string;
    /**
     * Unique order id
     * @type {string}
     * @memberof RegisterTxOneOf1Offramp
     */
    orderId: string;
}

/**
 * Check if a given object implements the RegisterTxOneOf1Offramp interface.
 */
export function instanceOfRegisterTxOneOf1Offramp(value: object): value is RegisterTxOneOf1Offramp {
    if (!('evmTxhash' in value) || value['evmTxhash'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    return true;
}

export function RegisterTxOneOf1OfframpFromJSON(json: any): RegisterTxOneOf1Offramp {
    return RegisterTxOneOf1OfframpFromJSONTyped(json, false);
}

export function RegisterTxOneOf1OfframpFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterTxOneOf1Offramp {
    if (json == null) {
        return json;
    }
    return {
        
        'evmTxhash': json['evm_txhash'],
        'orderId': json['order_id'],
    };
}

export function RegisterTxOneOf1OfframpToJSON(json: any): RegisterTxOneOf1Offramp {
    return RegisterTxOneOf1OfframpToJSONTyped(json, false);
}

export function RegisterTxOneOf1OfframpToJSONTyped(value?: RegisterTxOneOf1Offramp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evm_txhash': value['evmTxhash'],
        'order_id': value['orderId'],
    };
}

