/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RouteInfo
 */
export interface RouteInfo {
    /**
     *
     * @type {string}
     * @memberof RouteInfo
     */
    dstChain: string;
    /**
     *
     * @type {string}
     * @memberof RouteInfo
     */
    dstToken: string;
    /**
     *
     * @type {string}
     * @memberof RouteInfo
     */
    srcChain: string;
    /**
     *
     * @type {string}
     * @memberof RouteInfo
     */
    srcToken: string;
}

/**
 * Check if a given object implements the RouteInfo interface.
 */
export function instanceOfRouteInfo(value: object): value is RouteInfo {
    if (!('dstChain' in value) || value['dstChain'] === undefined) return false;
    if (!('dstToken' in value) || value['dstToken'] === undefined) return false;
    if (!('srcChain' in value) || value['srcChain'] === undefined) return false;
    if (!('srcToken' in value) || value['srcToken'] === undefined) return false;
    return true;
}

export function RouteInfoFromJSON(json: any): RouteInfo {
    return RouteInfoFromJSONTyped(json, false);
}

export function RouteInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteInfo {
    if (json == null) {
        return json;
    }
    return {
        dstChain: json['dstChain'],
        dstToken: json['dstToken'],
        srcChain: json['srcChain'],
        srcToken: json['srcToken'],
    };
}

export function RouteInfoToJSON(json: any): RouteInfo {
    return RouteInfoToJSONTyped(json, false);
}

export function RouteInfoToJSONTyped(value?: RouteInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        dstChain: value['dstChain'],
        dstToken: value['dstToken'],
        srcChain: value['srcChain'],
        srcToken: value['srcToken'],
    };
}
