/**

Generated by the following Solidity interface...
```solidity
interface SegWitUtils {
    function COINBASE_WITNESS_PK_SCRIPT_LENGTH() external view returns (uint256);
    function WITNESS_MAGIC_BYTES() external view returns (bytes6);
}
```

...which was generated by the following JSON ABI:
```json
[
  {
    "type": "function",
    "name": "COINBASE_WITNESS_PK_SCRIPT_LENGTH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "WITNESS_MAGIC_BYTES",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes6",
        "internalType": "bytes6"
      }
    ],
    "stateMutability": "view"
  }
]
```*/
#[allow(
    non_camel_case_types,
    non_snake_case,
    clippy::pub_underscore_fields,
    clippy::style
)]
pub mod SegWitUtils {
    use super::*;
    use alloy::sol_types as alloy_sol_types;
    /// The creation / init bytecode of the contract.
    ///
    /// ```text
    ///0x60e6610033600b8282823980515f1a607314602757634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603c575f3560e01c8063c6cd9637146040578063e0e2748a14605a575b5f5ffd5b6047602681565b6040519081526020015b60405180910390f35b60807f6a24aa21a9ed000000000000000000000000000000000000000000000000000081565b6040517fffffffffffff00000000000000000000000000000000000000000000000000009091168152602001605156fea2646970667358221220e58e240f9f1267ab125780b12ac8faab080fde8f5d56f8d0e9df358f145cc5e764736f6c634300081b0033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"`\xE6a\x003`\x0B\x82\x82\x829\x80Q_\x1A`s\x14`'WcNH{q`\xE0\x1B_R_`\x04R`$_\xFD[0_R`s\x81S\x82\x81\xF3\xFEs\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x000\x14`\x80`@R`\x046\x10`<W_5`\xE0\x1C\x80c\xC6\xCD\x967\x14`@W\x80c\xE0\xE2t\x8A\x14`ZW[__\xFD[`G`&\x81V[`@Q\x90\x81R` \x01[`@Q\x80\x91\x03\x90\xF3[`\x80\x7Fj$\xAA!\xA9\xED\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x81V[`@Q\x7F\xFF\xFF\xFF\xFF\xFF\xFF\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x90\x91\x16\x81R` \x01`QV\xFE\xA2dipfsX\"\x12 \xE5\x8E$\x0F\x9F\x12g\xAB\x12W\x80\xB1*\xC8\xFA\xAB\x08\x0F\xDE\x8F]V\xF8\xD0\xE9\xDF5\x8F\x14\\\xC5\xE7dsolcC\0\x08\x1B\x003",
    );
    /// The runtime bytecode of the contract, as deployed on the network.
    ///
    /// ```text
    ///0x7300000000000000000000000000000000000000003014608060405260043610603c575f3560e01c8063c6cd9637146040578063e0e2748a14605a575b5f5ffd5b6047602681565b6040519081526020015b60405180910390f35b60807f6a24aa21a9ed000000000000000000000000000000000000000000000000000081565b6040517fffffffffffff00000000000000000000000000000000000000000000000000009091168152602001605156fea2646970667358221220e58e240f9f1267ab125780b12ac8faab080fde8f5d56f8d0e9df358f145cc5e764736f6c634300081b0033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static DEPLOYED_BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"s\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x000\x14`\x80`@R`\x046\x10`<W_5`\xE0\x1C\x80c\xC6\xCD\x967\x14`@W\x80c\xE0\xE2t\x8A\x14`ZW[__\xFD[`G`&\x81V[`@Q\x90\x81R` \x01[`@Q\x80\x91\x03\x90\xF3[`\x80\x7Fj$\xAA!\xA9\xED\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x81V[`@Q\x7F\xFF\xFF\xFF\xFF\xFF\xFF\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x90\x91\x16\x81R` \x01`QV\xFE\xA2dipfsX\"\x12 \xE5\x8E$\x0F\x9F\x12g\xAB\x12W\x80\xB1*\xC8\xFA\xAB\x08\x0F\xDE\x8F]V\xF8\xD0\xE9\xDF5\x8F\x14\\\xC5\xE7dsolcC\0\x08\x1B\x003",
    );
    /**Function with signature `COINBASE_WITNESS_PK_SCRIPT_LENGTH()` and selector `0xc6cd9637`.
```solidity
function COINBASE_WITNESS_PK_SCRIPT_LENGTH() external view returns (uint256);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct COINBASE_WITNESS_PK_SCRIPT_LENGTHCall {}
    ///Container type for the return parameters of the [`COINBASE_WITNESS_PK_SCRIPT_LENGTH()`](COINBASE_WITNESS_PK_SCRIPT_LENGTHCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct COINBASE_WITNESS_PK_SCRIPT_LENGTHReturn {
        pub _0: alloy::sol_types::private::primitives::aliases::U256,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = ();
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = ();
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<COINBASE_WITNESS_PK_SCRIPT_LENGTHCall>
            for UnderlyingRustTuple<'_> {
                fn from(value: COINBASE_WITNESS_PK_SCRIPT_LENGTHCall) -> Self {
                    ()
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for COINBASE_WITNESS_PK_SCRIPT_LENGTHCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {}
                }
            }
        }
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::Uint<256>,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::primitives::aliases::U256,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<COINBASE_WITNESS_PK_SCRIPT_LENGTHReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: COINBASE_WITNESS_PK_SCRIPT_LENGTHReturn) -> Self {
                    (value._0,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for COINBASE_WITNESS_PK_SCRIPT_LENGTHReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { _0: tuple.0 }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for COINBASE_WITNESS_PK_SCRIPT_LENGTHCall {
            type Parameters<'a> = ();
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = COINBASE_WITNESS_PK_SCRIPT_LENGTHReturn;
            type ReturnTuple<'a> = (alloy::sol_types::sol_data::Uint<256>,);
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "COINBASE_WITNESS_PK_SCRIPT_LENGTH()";
            const SELECTOR: [u8; 4] = [198u8, 205u8, 150u8, 55u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                ()
            }
            #[inline]
            fn abi_decode_returns(
                data: &[u8],
                validate: bool,
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data, validate)
                    .map(Into::into)
            }
        }
    };
    /**Function with signature `WITNESS_MAGIC_BYTES()` and selector `0xe0e2748a`.
```solidity
function WITNESS_MAGIC_BYTES() external view returns (bytes6);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct WITNESS_MAGIC_BYTESCall {}
    ///Container type for the return parameters of the [`WITNESS_MAGIC_BYTES()`](WITNESS_MAGIC_BYTESCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct WITNESS_MAGIC_BYTESReturn {
        pub _0: alloy::sol_types::private::FixedBytes<6>,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = ();
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = ();
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<WITNESS_MAGIC_BYTESCall>
            for UnderlyingRustTuple<'_> {
                fn from(value: WITNESS_MAGIC_BYTESCall) -> Self {
                    ()
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for WITNESS_MAGIC_BYTESCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {}
                }
            }
        }
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<6>,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (alloy::sol_types::private::FixedBytes<6>,);
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<WITNESS_MAGIC_BYTESReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: WITNESS_MAGIC_BYTESReturn) -> Self {
                    (value._0,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for WITNESS_MAGIC_BYTESReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { _0: tuple.0 }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for WITNESS_MAGIC_BYTESCall {
            type Parameters<'a> = ();
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = WITNESS_MAGIC_BYTESReturn;
            type ReturnTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<6>,);
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "WITNESS_MAGIC_BYTES()";
            const SELECTOR: [u8; 4] = [224u8, 226u8, 116u8, 138u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                ()
            }
            #[inline]
            fn abi_decode_returns(
                data: &[u8],
                validate: bool,
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data, validate)
                    .map(Into::into)
            }
        }
    };
    ///Container for all the [`SegWitUtils`](self) function calls.
    pub enum SegWitUtilsCalls {
        COINBASE_WITNESS_PK_SCRIPT_LENGTH(COINBASE_WITNESS_PK_SCRIPT_LENGTHCall),
        WITNESS_MAGIC_BYTES(WITNESS_MAGIC_BYTESCall),
    }
    #[automatically_derived]
    impl SegWitUtilsCalls {
        /// All the selectors of this enum.
        ///
        /// Note that the selectors might not be in the same order as the variants.
        /// No guarantees are made about the order of the selectors.
        ///
        /// Prefer using `SolInterface` methods instead.
        pub const SELECTORS: &'static [[u8; 4usize]] = &[
            [198u8, 205u8, 150u8, 55u8],
            [224u8, 226u8, 116u8, 138u8],
        ];
    }
    #[automatically_derived]
    impl alloy_sol_types::SolInterface for SegWitUtilsCalls {
        const NAME: &'static str = "SegWitUtilsCalls";
        const MIN_DATA_LENGTH: usize = 0usize;
        const COUNT: usize = 2usize;
        #[inline]
        fn selector(&self) -> [u8; 4] {
            match self {
                Self::COINBASE_WITNESS_PK_SCRIPT_LENGTH(_) => {
                    <COINBASE_WITNESS_PK_SCRIPT_LENGTHCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::WITNESS_MAGIC_BYTES(_) => {
                    <WITNESS_MAGIC_BYTESCall as alloy_sol_types::SolCall>::SELECTOR
                }
            }
        }
        #[inline]
        fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
            Self::SELECTORS.get(i).copied()
        }
        #[inline]
        fn valid_selector(selector: [u8; 4]) -> bool {
            Self::SELECTORS.binary_search(&selector).is_ok()
        }
        #[inline]
        #[allow(unsafe_code, non_snake_case)]
        fn abi_decode_raw(
            selector: [u8; 4],
            data: &[u8],
            validate: bool,
        ) -> alloy_sol_types::Result<Self> {
            static DECODE_SHIMS: &[fn(
                &[u8],
                bool,
            ) -> alloy_sol_types::Result<SegWitUtilsCalls>] = &[
                {
                    fn COINBASE_WITNESS_PK_SCRIPT_LENGTH(
                        data: &[u8],
                        validate: bool,
                    ) -> alloy_sol_types::Result<SegWitUtilsCalls> {
                        <COINBASE_WITNESS_PK_SCRIPT_LENGTHCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                                validate,
                            )
                            .map(SegWitUtilsCalls::COINBASE_WITNESS_PK_SCRIPT_LENGTH)
                    }
                    COINBASE_WITNESS_PK_SCRIPT_LENGTH
                },
                {
                    fn WITNESS_MAGIC_BYTES(
                        data: &[u8],
                        validate: bool,
                    ) -> alloy_sol_types::Result<SegWitUtilsCalls> {
                        <WITNESS_MAGIC_BYTESCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                                validate,
                            )
                            .map(SegWitUtilsCalls::WITNESS_MAGIC_BYTES)
                    }
                    WITNESS_MAGIC_BYTES
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(
                    alloy_sol_types::Error::unknown_selector(
                        <Self as alloy_sol_types::SolInterface>::NAME,
                        selector,
                    ),
                );
            };
            (unsafe { DECODE_SHIMS.get_unchecked(idx) })(data, validate)
        }
        #[inline]
        fn abi_encoded_size(&self) -> usize {
            match self {
                Self::COINBASE_WITNESS_PK_SCRIPT_LENGTH(inner) => {
                    <COINBASE_WITNESS_PK_SCRIPT_LENGTHCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::WITNESS_MAGIC_BYTES(inner) => {
                    <WITNESS_MAGIC_BYTESCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
            }
        }
        #[inline]
        fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
            match self {
                Self::COINBASE_WITNESS_PK_SCRIPT_LENGTH(inner) => {
                    <COINBASE_WITNESS_PK_SCRIPT_LENGTHCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::WITNESS_MAGIC_BYTES(inner) => {
                    <WITNESS_MAGIC_BYTESCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
            }
        }
    }
    use alloy::contract as alloy_contract;
    /**Creates a new wrapper around an on-chain [`SegWitUtils`](self) contract instance.

See the [wrapper's documentation](`SegWitUtilsInstance`) for more details.*/
    #[inline]
    pub const fn new<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    >(
        address: alloy_sol_types::private::Address,
        provider: P,
    ) -> SegWitUtilsInstance<T, P, N> {
        SegWitUtilsInstance::<T, P, N>::new(address, provider)
    }
    /**Deploys this contract using the given `provider` and constructor arguments, if any.

Returns a new instance of the contract, if the deployment was successful.

For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
    #[inline]
    pub fn deploy<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    >(
        provider: P,
    ) -> impl ::core::future::Future<
        Output = alloy_contract::Result<SegWitUtilsInstance<T, P, N>>,
    > {
        SegWitUtilsInstance::<T, P, N>::deploy(provider)
    }
    /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
and constructor arguments, if any.

This is a simple wrapper around creating a `RawCallBuilder` with the data set to
the bytecode concatenated with the constructor's ABI-encoded arguments.*/
    #[inline]
    pub fn deploy_builder<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    >(provider: P) -> alloy_contract::RawCallBuilder<T, P, N> {
        SegWitUtilsInstance::<T, P, N>::deploy_builder(provider)
    }
    /**A [`SegWitUtils`](self) instance.

Contains type-safe methods for interacting with an on-chain instance of the
[`SegWitUtils`](self) contract located at a given `address`, using a given
provider `P`.

If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
documentation on how to provide it), the `deploy` and `deploy_builder` methods can
be used to deploy a new instance of the contract.

See the [module-level documentation](self) for all the available methods.*/
    #[derive(Clone)]
    pub struct SegWitUtilsInstance<T, P, N = alloy_contract::private::Ethereum> {
        address: alloy_sol_types::private::Address,
        provider: P,
        _network_transport: ::core::marker::PhantomData<(N, T)>,
    }
    #[automatically_derived]
    impl<T, P, N> ::core::fmt::Debug for SegWitUtilsInstance<T, P, N> {
        #[inline]
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_tuple("SegWitUtilsInstance").field(&self.address).finish()
        }
    }
    /// Instantiation and getters/setters.
    #[automatically_derived]
    impl<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    > SegWitUtilsInstance<T, P, N> {
        /**Creates a new wrapper around an on-chain [`SegWitUtils`](self) contract instance.

See the [wrapper's documentation](`SegWitUtilsInstance`) for more details.*/
        #[inline]
        pub const fn new(
            address: alloy_sol_types::private::Address,
            provider: P,
        ) -> Self {
            Self {
                address,
                provider,
                _network_transport: ::core::marker::PhantomData,
            }
        }
        /**Deploys this contract using the given `provider` and constructor arguments, if any.

Returns a new instance of the contract, if the deployment was successful.

For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
        #[inline]
        pub async fn deploy(
            provider: P,
        ) -> alloy_contract::Result<SegWitUtilsInstance<T, P, N>> {
            let call_builder = Self::deploy_builder(provider);
            let contract_address = call_builder.deploy().await?;
            Ok(Self::new(contract_address, call_builder.provider))
        }
        /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
and constructor arguments, if any.

This is a simple wrapper around creating a `RawCallBuilder` with the data set to
the bytecode concatenated with the constructor's ABI-encoded arguments.*/
        #[inline]
        pub fn deploy_builder(provider: P) -> alloy_contract::RawCallBuilder<T, P, N> {
            alloy_contract::RawCallBuilder::new_raw_deploy(
                provider,
                ::core::clone::Clone::clone(&BYTECODE),
            )
        }
        /// Returns a reference to the address.
        #[inline]
        pub const fn address(&self) -> &alloy_sol_types::private::Address {
            &self.address
        }
        /// Sets the address.
        #[inline]
        pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
            self.address = address;
        }
        /// Sets the address and returns `self`.
        pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
            self.set_address(address);
            self
        }
        /// Returns a reference to the provider.
        #[inline]
        pub const fn provider(&self) -> &P {
            &self.provider
        }
    }
    impl<T, P: ::core::clone::Clone, N> SegWitUtilsInstance<T, &P, N> {
        /// Clones the provider and returns a new instance with the cloned provider.
        #[inline]
        pub fn with_cloned_provider(self) -> SegWitUtilsInstance<T, P, N> {
            SegWitUtilsInstance {
                address: self.address,
                provider: ::core::clone::Clone::clone(&self.provider),
                _network_transport: ::core::marker::PhantomData,
            }
        }
    }
    /// Function calls.
    #[automatically_derived]
    impl<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    > SegWitUtilsInstance<T, P, N> {
        /// Creates a new call builder using this contract instance's provider and address.
        ///
        /// Note that the call can be any function call, not just those defined in this
        /// contract. Prefer using the other methods for building type-safe contract calls.
        pub fn call_builder<C: alloy_sol_types::SolCall>(
            &self,
            call: &C,
        ) -> alloy_contract::SolCallBuilder<T, &P, C, N> {
            alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
        }
        ///Creates a new call builder for the [`COINBASE_WITNESS_PK_SCRIPT_LENGTH`] function.
        pub fn COINBASE_WITNESS_PK_SCRIPT_LENGTH(
            &self,
        ) -> alloy_contract::SolCallBuilder<
            T,
            &P,
            COINBASE_WITNESS_PK_SCRIPT_LENGTHCall,
            N,
        > {
            self.call_builder(
                &COINBASE_WITNESS_PK_SCRIPT_LENGTHCall {
                },
            )
        }
        ///Creates a new call builder for the [`WITNESS_MAGIC_BYTES`] function.
        pub fn WITNESS_MAGIC_BYTES(
            &self,
        ) -> alloy_contract::SolCallBuilder<T, &P, WITNESS_MAGIC_BYTESCall, N> {
            self.call_builder(&WITNESS_MAGIC_BYTESCall {})
        }
    }
    /// Event filters.
    #[automatically_derived]
    impl<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    > SegWitUtilsInstance<T, P, N> {
        /// Creates a new event filter using this contract instance's provider and address.
        ///
        /// Note that the type can be any event, not just those defined in this contract.
        /// Prefer using the other methods for building type-safe event filters.
        pub fn event_filter<E: alloy_sol_types::SolEvent>(
            &self,
        ) -> alloy_contract::Event<T, &P, E, N> {
            alloy_contract::Event::new_sol(&self.provider, &self.address)
        }
    }
}
