/* tslint:disable */
/* eslint-disable */
/**
 * gateway-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
    OrderStatusToJSONTyped,
} from './OrderStatus';
import type { TxInfo } from './TxInfo';
import {
    TxInfoFromJSON,
    TxInfoFromJSONTyped,
    TxInfoToJSON,
    TxInfoToJSONTyped,
} from './TxInfo';
import type { ChainDetails } from './ChainDetails';
import {
    ChainDetailsFromJSON,
    ChainDetailsFromJSONTyped,
    ChainDetailsToJSON,
    ChainDetailsToJSONTyped,
} from './ChainDetails';

/**
 * 
 * @export
 * @interface GatewayOrderInfoOneOf1Offramp
 */
export interface GatewayOrderInfoOneOf1Offramp {
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    bitcoinExplorerUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    bobExplorerUrl: string;
    /**
     * 
     * @type {TxInfo}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    bumpFeeTx?: TxInfo | null;
    /**
     * 
     * @type {ChainDetails}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    destinationChain: ChainDetails;
    /**
     * 
     * @type {boolean}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    done: boolean;
    /**
     * 
     * @type {number}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    estimatedTimeInSecs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    feeInSats: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    offrampRegistryAddress: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    orderId: string;
    /**
     * 
     * @type {TxInfo}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    refundOrderTx?: TxInfo | null;
    /**
     * 
     * @type {ChainDetails}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    sourceChain: ChainDetails;
    /**
     * 
     * @type {OrderStatus}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    status?: OrderStatus | null;
    /**
     * 
     * @type {number}
     * @memberof GatewayOrderInfoOneOf1Offramp
     */
    timestamp: number;
}



/**
 * Check if a given object implements the GatewayOrderInfoOneOf1Offramp interface.
 */
export function instanceOfGatewayOrderInfoOneOf1Offramp(value: object): value is GatewayOrderInfoOneOf1Offramp {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('bobExplorerUrl' in value) || value['bobExplorerUrl'] === undefined) return false;
    if (!('destinationChain' in value) || value['destinationChain'] === undefined) return false;
    if (!('done' in value) || value['done'] === undefined) return false;
    if (!('feeInSats' in value) || value['feeInSats'] === undefined) return false;
    if (!('offrampRegistryAddress' in value) || value['offrampRegistryAddress'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('sourceChain' in value) || value['sourceChain'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function GatewayOrderInfoOneOf1OfframpFromJSON(json: any): GatewayOrderInfoOneOf1Offramp {
    return GatewayOrderInfoOneOf1OfframpFromJSONTyped(json, false);
}

export function GatewayOrderInfoOneOf1OfframpFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayOrderInfoOneOf1Offramp {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'bitcoinExplorerUrl': json['bitcoin_explorer_url'] == null ? undefined : json['bitcoin_explorer_url'],
        'bobExplorerUrl': json['bob_explorer_url'],
        'bumpFeeTx': json['bump_fee_tx'] == null ? undefined : TxInfoFromJSON(json['bump_fee_tx']),
        'destinationChain': ChainDetailsFromJSON(json['destination_chain']),
        'done': json['done'],
        'estimatedTimeInSecs': json['estimated_time_in_secs'] == null ? undefined : json['estimated_time_in_secs'],
        'feeInSats': json['fee_in_sats'],
        'offrampRegistryAddress': json['offramp_registry_address'],
        'orderId': json['order_id'],
        'refundOrderTx': json['refund_order_tx'] == null ? undefined : TxInfoFromJSON(json['refund_order_tx']),
        'sourceChain': ChainDetailsFromJSON(json['source_chain']),
        'status': json['status'] == null ? undefined : OrderStatusFromJSON(json['status']),
        'timestamp': json['timestamp'],
    };
}

export function GatewayOrderInfoOneOf1OfframpToJSON(json: any): GatewayOrderInfoOneOf1Offramp {
    return GatewayOrderInfoOneOf1OfframpToJSONTyped(json, false);
}

export function GatewayOrderInfoOneOf1OfframpToJSONTyped(value?: GatewayOrderInfoOneOf1Offramp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'bitcoin_explorer_url': value['bitcoinExplorerUrl'],
        'bob_explorer_url': value['bobExplorerUrl'],
        'bump_fee_tx': TxInfoToJSON(value['bumpFeeTx']),
        'destination_chain': ChainDetailsToJSON(value['destinationChain']),
        'done': value['done'],
        'estimated_time_in_secs': value['estimatedTimeInSecs'],
        'fee_in_sats': value['feeInSats'],
        'offramp_registry_address': value['offrampRegistryAddress'],
        'order_id': value['orderId'],
        'refund_order_tx': TxInfoToJSON(value['refundOrderTx']),
        'source_chain': ChainDetailsToJSON(value['sourceChain']),
        'status': OrderStatusToJSON(value['status']),
        'timestamp': value['timestamp'],
    };
}

