/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GatewayCreateOrder,
  GatewayError,
  GatewayErrorV2,
  GatewayMaxSpendable,
  GatewayOrderInfo,
  GatewayQuoteV2,
  PaginatedOrdersResponse,
  RegisterTx,
  RegisterTxSuccess,
  RouteInfo,
} from '../models/index';
import {
    GatewayCreateOrderFromJSON,
    GatewayCreateOrderToJSON,
    GatewayErrorFromJSON,
    GatewayErrorToJSON,
    GatewayErrorV2FromJSON,
    GatewayErrorV2ToJSON,
    GatewayMaxSpendableFromJSON,
    GatewayMaxSpendableToJSON,
    GatewayOrderInfoFromJSON,
    GatewayOrderInfoToJSON,
    GatewayQuoteV2FromJSON,
    GatewayQuoteV2ToJSON,
    PaginatedOrdersResponseFromJSON,
    PaginatedOrdersResponseToJSON,
    RegisterTxFromJSON,
    RegisterTxToJSON,
    RegisterTxSuccessFromJSON,
    RegisterTxSuccessToJSON,
    RouteInfoFromJSON,
    RouteInfoToJSON,
} from '../models/index';

export interface CreateOrderV2Request {
    gatewayQuoteV2: GatewayQuoteV2;
}

export interface GetMaxSpendableRequest {
    address: string;
}

export interface GetOrderRequest {
    id: string;
}

export interface GetOrdersV2Request {
    userAddress: string;
    cursor: string;
    limit?: number;
}

export interface GetQuoteV2Request {
    srcChain: string;
    dstChain: string;
    recipient: string;
    srcToken: string;
    dstToken: string;
    amount: string;
    slippage: string;
    sender?: string;
    gasRefill?: string;
    strategyTarget?: string;
    strategyMessage?: string;
    affiliateId?: string;
}

export interface RegisterTxRequest {
    registerTx: RegisterTx;
}

/**
 * 
 */
export class V2Api extends runtime.BaseAPI {

    /**
     * Creates a new request, reserves the required liquidity.
     * Create a new gateway order.
     */
    async createOrderV2Raw(requestParameters: CreateOrderV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayCreateOrder>> {
        if (requestParameters['gatewayQuoteV2'] == null) {
            throw new runtime.RequiredError(
                'gatewayQuoteV2',
                'Required parameter "gatewayQuoteV2" was null or undefined when calling createOrderV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/create-order`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GatewayQuoteV2ToJSON(requestParameters['gatewayQuoteV2']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayCreateOrderFromJSON(jsonValue));
    }

    /**
     * Creates a new request, reserves the required liquidity.
     * Create a new gateway order.
     */
    async createOrderV2(requestParameters: CreateOrderV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayCreateOrder> {
        const response = await this.createOrderV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMaxSpendableRaw(requestParameters: GetMaxSpendableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayMaxSpendable>> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getMaxSpendable().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("api_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/get-max-spendable/{address}`;
        urlPath = urlPath.replace(`{${"address"}}`, encodeURIComponent(String(requestParameters['address'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayMaxSpendableFromJSON(jsonValue));
    }

    /**
     */
    async getMaxSpendable(requestParameters: GetMaxSpendableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayMaxSpendable> {
        const response = await this.getMaxSpendableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all orders for a specific ID.
     */
    async getOrderRaw(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayOrderInfo>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("api_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/get-order/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayOrderInfoFromJSON(jsonValue));
    }

    /**
     * Get all orders for a specific ID.
     */
    async getOrder(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayOrderInfo> {
        const response = await this.getOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user orders with pagination (v2).
     */
    async getOrdersV2Raw(requestParameters: GetOrdersV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedOrdersResponse>> {
        if (requestParameters['userAddress'] == null) {
            throw new runtime.RequiredError(
                'userAddress',
                'Required parameter "userAddress" was null or undefined when calling getOrdersV2().'
            );
        }

        if (requestParameters['cursor'] == null) {
            throw new runtime.RequiredError(
                'cursor',
                'Required parameter "cursor" was null or undefined when calling getOrdersV2().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("api_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/get-orders/{user_address}`;
        urlPath = urlPath.replace(`{${"user_address"}}`, encodeURIComponent(String(requestParameters['userAddress'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedOrdersResponseFromJSON(jsonValue));
    }

    /**
     * Get user orders with pagination (v2).
     */
    async getOrdersV2(requestParameters: GetOrdersV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedOrdersResponse> {
        const response = await this.getOrdersV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Checks the available liquidity and provides a quote.
     * Get a gateway quote.
     */
    async getQuoteV2Raw(requestParameters: GetQuoteV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayQuoteV2>> {
        if (requestParameters['srcChain'] == null) {
            throw new runtime.RequiredError(
                'srcChain',
                'Required parameter "srcChain" was null or undefined when calling getQuoteV2().'
            );
        }

        if (requestParameters['dstChain'] == null) {
            throw new runtime.RequiredError(
                'dstChain',
                'Required parameter "dstChain" was null or undefined when calling getQuoteV2().'
            );
        }

        if (requestParameters['recipient'] == null) {
            throw new runtime.RequiredError(
                'recipient',
                'Required parameter "recipient" was null or undefined when calling getQuoteV2().'
            );
        }

        if (requestParameters['srcToken'] == null) {
            throw new runtime.RequiredError(
                'srcToken',
                'Required parameter "srcToken" was null or undefined when calling getQuoteV2().'
            );
        }

        if (requestParameters['dstToken'] == null) {
            throw new runtime.RequiredError(
                'dstToken',
                'Required parameter "dstToken" was null or undefined when calling getQuoteV2().'
            );
        }

        if (requestParameters['amount'] == null) {
            throw new runtime.RequiredError(
                'amount',
                'Required parameter "amount" was null or undefined when calling getQuoteV2().'
            );
        }

        if (requestParameters['slippage'] == null) {
            throw new runtime.RequiredError(
                'slippage',
                'Required parameter "slippage" was null or undefined when calling getQuoteV2().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['srcChain'] != null) {
            queryParameters['srcChain'] = requestParameters['srcChain'];
        }

        if (requestParameters['dstChain'] != null) {
            queryParameters['dstChain'] = requestParameters['dstChain'];
        }

        if (requestParameters['sender'] != null) {
            queryParameters['sender'] = requestParameters['sender'];
        }

        if (requestParameters['recipient'] != null) {
            queryParameters['recipient'] = requestParameters['recipient'];
        }

        if (requestParameters['srcToken'] != null) {
            queryParameters['srcToken'] = requestParameters['srcToken'];
        }

        if (requestParameters['dstToken'] != null) {
            queryParameters['dstToken'] = requestParameters['dstToken'];
        }

        if (requestParameters['amount'] != null) {
            queryParameters['amount'] = requestParameters['amount'];
        }

        if (requestParameters['gasRefill'] != null) {
            queryParameters['gasRefill'] = requestParameters['gasRefill'];
        }

        if (requestParameters['slippage'] != null) {
            queryParameters['slippage'] = requestParameters['slippage'];
        }

        if (requestParameters['strategyTarget'] != null) {
            queryParameters['strategyTarget'] = requestParameters['strategyTarget'];
        }

        if (requestParameters['strategyMessage'] != null) {
            queryParameters['strategyMessage'] = requestParameters['strategyMessage'];
        }

        if (requestParameters['affiliateId'] != null) {
            queryParameters['affiliateId'] = requestParameters['affiliateId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/get-quote`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayQuoteV2FromJSON(jsonValue));
    }

    /**
     * Checks the available liquidity and provides a quote.
     * Get a gateway quote.
     */
    async getQuoteV2(requestParameters: GetQuoteV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayQuoteV2> {
        const response = await this.getQuoteV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all supported routes.
     */
    async getRoutesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RouteInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("api_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/get-routes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RouteInfoFromJSON));
    }

    /**
     * Get all supported routes.
     */
    async getRoutes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RouteInfo>> {
        const response = await this.getRoutesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Required for the Solver to track and execute some requests.
     * Register a tx for a request.
     */
    async registerTxRaw(requestParameters: RegisterTxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterTxSuccess>> {
        if (requestParameters['registerTx'] == null) {
            throw new runtime.RequiredError(
                'registerTx',
                'Required parameter "registerTx" was null or undefined when calling registerTx().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("api_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/register-tx`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterTxToJSON(requestParameters['registerTx']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterTxSuccessFromJSON(jsonValue));
    }

    /**
     * Required for the Solver to track and execute some requests.
     * Register a tx for a request.
     */
    async registerTx(requestParameters: RegisterTxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterTxSuccess> {
        const response = await this.registerTxRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
