/* tslint:disable */
/* eslint-disable */
/**
 * BOB Gateway API
 * BOB Gateway API for Bitcoin swaps
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GatewayCreateOrderV2,
  GatewayErrorV2,
  GatewayErrorV3,
  GatewayMaxSpendable,
  GatewayOrderInfoV2,
  GatewayQuoteV3,
  PaginatedOrdersResponse,
  RegisterTxSuccess,
  RegisterTxV2,
  RouteInfo,
} from '../models/index';
import {
    GatewayCreateOrderV2FromJSON,
    GatewayCreateOrderV2ToJSON,
    GatewayErrorV2FromJSON,
    GatewayErrorV2ToJSON,
    GatewayErrorV3FromJSON,
    GatewayErrorV3ToJSON,
    GatewayMaxSpendableFromJSON,
    GatewayMaxSpendableToJSON,
    GatewayOrderInfoV2FromJSON,
    GatewayOrderInfoV2ToJSON,
    GatewayQuoteV3FromJSON,
    GatewayQuoteV3ToJSON,
    PaginatedOrdersResponseFromJSON,
    PaginatedOrdersResponseToJSON,
    RegisterTxSuccessFromJSON,
    RegisterTxSuccessToJSON,
    RegisterTxV2FromJSON,
    RegisterTxV2ToJSON,
    RouteInfoFromJSON,
    RouteInfoToJSON,
} from '../models/index';

export interface CreateOrderV3Request {
    gatewayQuoteV3: GatewayQuoteV3;
}

export interface GetMaxSpendableV2Request {
    address: string;
}

export interface GetOrderV2Request {
    id: string;
}

export interface GetOrdersV2Request {
    userAddress: string;
    cursor?: string;
    limit?: number;
}

export interface GetQuoteV3Request {
    srcChain: string;
    dstChain: string;
    recipient: string;
    srcToken: string;
    dstToken: string;
    amount: string;
    slippage: string;
    ownerAddress: string;
    sender?: string;
    gasRefill?: string;
    affiliates?: string;
}

export interface RegisterTxV3Request {
    registerTxV2: RegisterTxV2;
}

/**
 * 
 */
export class V3Api extends runtime.BaseAPI {

    /**
     * Accepts a `GatewayQuoteV3` — the signed V3 quote with `ownerAddress` embedded in each variant.
     * Create a new gateway order (V3).
     */
    async createOrderV3Raw(requestParameters: CreateOrderV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayCreateOrderV2>> {
        if (requestParameters['gatewayQuoteV3'] == null) {
            throw new runtime.RequiredError(
                'gatewayQuoteV3',
                'Required parameter "gatewayQuoteV3" was null or undefined when calling createOrderV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v3/create-order`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GatewayQuoteV3ToJSON(requestParameters['gatewayQuoteV3']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayCreateOrderV2FromJSON(jsonValue));
    }

    /**
     * Accepts a `GatewayQuoteV3` — the signed V3 quote with `ownerAddress` embedded in each variant.
     * Create a new gateway order (V3).
     */
    async createOrderV3(requestParameters: CreateOrderV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayCreateOrderV2> {
        const response = await this.createOrderV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the maximum spendable Bitcoin amount for the given address (v2).
     */
    async getMaxSpendableV2Raw(requestParameters: GetMaxSpendableV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayMaxSpendable>> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getMaxSpendableV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("api_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v3/get-max-spendable/{address}`;
        urlPath = urlPath.replace(`{${"address"}}`, encodeURIComponent(String(requestParameters['address'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayMaxSpendableFromJSON(jsonValue));
    }

    /**
     * Get the maximum spendable Bitcoin amount for the given address (v2).
     */
    async getMaxSpendableV2(requestParameters: GetMaxSpendableV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayMaxSpendable> {
        const response = await this.getMaxSpendableV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get an order by id (v2).
     */
    async getOrderV2Raw(requestParameters: GetOrderV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayOrderInfoV2>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrderV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("api_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v3/get-order/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayOrderInfoV2FromJSON(jsonValue));
    }

    /**
     * Get an order by id (v2).
     */
    async getOrderV2(requestParameters: GetOrderV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayOrderInfoV2> {
        const response = await this.getOrderV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user orders (v2).
     */
    async getOrdersV2Raw(requestParameters: GetOrdersV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedOrdersResponse>> {
        if (requestParameters['userAddress'] == null) {
            throw new runtime.RequiredError(
                'userAddress',
                'Required parameter "userAddress" was null or undefined when calling getOrdersV2().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("api_key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v3/get-orders/{user_address}`;
        urlPath = urlPath.replace(`{${"user_address"}}`, encodeURIComponent(String(requestParameters['userAddress'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedOrdersResponseFromJSON(jsonValue));
    }

    /**
     * Get user orders (v2).
     */
    async getOrdersV2(requestParameters: GetOrdersV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedOrdersResponse> {
        const response = await this.getOrdersV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a gateway quote (v3 — requires `ownerAddress`).
     */
    async getQuoteV3Raw(requestParameters: GetQuoteV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GatewayQuoteV3>> {
        if (requestParameters['srcChain'] == null) {
            throw new runtime.RequiredError(
                'srcChain',
                'Required parameter "srcChain" was null or undefined when calling getQuoteV3().'
            );
        }

        if (requestParameters['dstChain'] == null) {
            throw new runtime.RequiredError(
                'dstChain',
                'Required parameter "dstChain" was null or undefined when calling getQuoteV3().'
            );
        }

        if (requestParameters['recipient'] == null) {
            throw new runtime.RequiredError(
                'recipient',
                'Required parameter "recipient" was null or undefined when calling getQuoteV3().'
            );
        }

        if (requestParameters['srcToken'] == null) {
            throw new runtime.RequiredError(
                'srcToken',
                'Required parameter "srcToken" was null or undefined when calling getQuoteV3().'
            );
        }

        if (requestParameters['dstToken'] == null) {
            throw new runtime.RequiredError(
                'dstToken',
                'Required parameter "dstToken" was null or undefined when calling getQuoteV3().'
            );
        }

        if (requestParameters['amount'] == null) {
            throw new runtime.RequiredError(
                'amount',
                'Required parameter "amount" was null or undefined when calling getQuoteV3().'
            );
        }

        if (requestParameters['slippage'] == null) {
            throw new runtime.RequiredError(
                'slippage',
                'Required parameter "slippage" was null or undefined when calling getQuoteV3().'
            );
        }

        if (requestParameters['ownerAddress'] == null) {
            throw new runtime.RequiredError(
                'ownerAddress',
                'Required parameter "ownerAddress" was null or undefined when calling getQuoteV3().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['srcChain'] != null) {
            queryParameters['srcChain'] = requestParameters['srcChain'];
        }

        if (requestParameters['dstChain'] != null) {
            queryParameters['dstChain'] = requestParameters['dstChain'];
        }

        if (requestParameters['sender'] != null) {
            queryParameters['sender'] = requestParameters['sender'];
        }

        if (requestParameters['recipient'] != null) {
            queryParameters['recipient'] = requestParameters['recipient'];
        }

        if (requestParameters['srcToken'] != null) {
            queryParameters['srcToken'] = requestParameters['srcToken'];
        }

        if (requestParameters['dstToken'] != null) {
            queryParameters['dstToken'] = requestParameters['dstToken'];
        }

        if (requestParameters['amount'] != null) {
            queryParameters['amount'] = requestParameters['amount'];
        }

        if (requestParameters['gasRefill'] != null) {
            queryParameters['gasRefill'] = requestParameters['gasRefill'];
        }

        if (requestParameters['slippage'] != null) {
            queryParameters['slippage'] = requestParameters['slippage'];
        }

        if (requestParameters['affiliates'] != null) {
            queryParameters['affiliates'] = requestParameters['affiliates'];
        }

        if (requestParameters['ownerAddress'] != null) {
            queryParameters['ownerAddress'] = requestParameters['ownerAddress'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v3/get-quote`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayQuoteV3FromJSON(jsonValue));
    }

    /**
     * Get a gateway quote (v3 — requires `ownerAddress`).
     */
    async getQuoteV3(requestParameters: GetQuoteV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GatewayQuoteV3> {
        const response = await this.getQuoteV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all supported routes (v3).
     */
    async getRoutesV3Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RouteInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v3/get-routes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RouteInfoFromJSON));
    }

    /**
     * Get all supported routes (v3).
     */
    async getRoutesV3(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RouteInfo>> {
        const response = await this.getRoutesV3Raw(initOverrides);
        return await response.value();
    }

    /**
     * Register a tx for a request (V3 body; identical shape to V2).
     */
    async registerTxV3Raw(requestParameters: RegisterTxV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterTxSuccess>> {
        if (requestParameters['registerTxV2'] == null) {
            throw new runtime.RequiredError(
                'registerTxV2',
                'Required parameter "registerTxV2" was null or undefined when calling registerTxV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v3/register-tx`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterTxV2ToJSON(requestParameters['registerTxV2']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterTxSuccessFromJSON(jsonValue));
    }

    /**
     * Register a tx for a request (V3 body; identical shape to V2).
     */
    async registerTxV3(requestParameters: RegisterTxV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterTxSuccess> {
        const response = await this.registerTxV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
