name: SDK

on: [pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: sdk/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: npx prettier --check {examples,src,test}
      - run: pnpm lint
      - name: Run tests
        run: pnpm test
